# Generated by Django 5.2.11 on 2026-05-21 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0046_convert_colorblind_disability_to_bool'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="URL-safe slug, e.g. 'b40-2026'", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name, e.g. 'B40 Assistance Programme 2026'", max_length=200)),
                ('year', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True, help_text='Currently accepting new applications')),
                ('min_spm_a_count', models.IntegerField(default=5, help_text="Minimum SPM A's (A+/A/A- all count) for Bucket A")),
                ('min_stpm_pngk', models.FloatField(default=3.0, help_text='Minimum STPM PNGK for Bucket A')),
                ('income_ceiling', models.IntegerField(blank=True, help_text='B40 monthly household income ceiling in RM', null=True)),
                ('bucket_b_margin', models.IntegerField(default=1, help_text="How many A's short of min_spm_a_count still qualifies for Bucket B")),
                ('funding_envelope', models.IntegerField(blank=True, help_text='Per-student funding envelope in RM', null=True)),
                ('fail_email_delay_days', models.IntegerField(default=3, help_text="Days to wait before the 'not this round' email (Sprint 3)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scholarship_cohorts',
                'ordering': ['-year', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('spm', 'SPM'), ('stpm', 'STPM')], default='spm', max_length=10)),
                ('spm_a_count', models.IntegerField(blank=True, help_text="Snapshot of SPM A's at apply time (A+/A/A- all count)", null=True)),
                ('stpm_pngk', models.FloatField(blank=True, null=True)),
                ('household_income', models.IntegerField(blank=True, help_text='Combined monthly household income in RM', null=True)),
                ('household_size', models.IntegerField(blank=True, null=True)),
                ('receives_str', models.BooleanField(default=False, help_text='Active Sumbangan Tunai Rahmah recipient (B40 anchor)')),
                ('receives_jkm', models.BooleanField(default=False, help_text='Receives JKM assistance')),
                ('intended_pathway', models.CharField(blank=True, default='', help_text='e.g. asasi, matrik, stpm, pismp, diploma, degree', max_length=50)),
                ('intends_tertiary_2026', models.BooleanField(default=True)),
                ('consent_to_contact', models.BooleanField(default=False, help_text='Consent to be contacted about this application (sponsor-sharing consent is collected later)')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20)),
                ('bucket', models.CharField(blank=True, choices=[('', 'Unassigned'), ('A', 'Bucket A'), ('B', 'Bucket B')], default='', max_length=1)),
                ('shortlist_reason', models.TextField(blank=True, default='', help_text='Set by the shortlisting engine (which criterion missed)')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('form_data', models.JSONField(blank=True, default=dict, help_text='Raw/extra intake fields from the native form')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, help_text='Linked HalaTuju profile (always set in the apply-first flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarship_applications', to='courses.studentprofile')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='scholarship.scholarshipcohort')),
            ],
            options={
                'db_table': 'scholarship_applications',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('profile__isnull', False)), fields=('cohort', 'profile'), name='unique_application_per_cohort')],
            },
        ),
    ]
