# Generated by Django 5.2.11 on 2026-05-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='decision_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the pass/fail decision email was sent', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='locale',
            field=models.CharField(default='en', help_text="Applicant's language at apply time (en/ms/ta) for deferred emails", max_length=2),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='notify_email',
            field=models.EmailField(blank=True, default='', help_text='Resolved contact email captured at submit (for the deferred fail email)', max_length=254),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='shortlisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
