# Generated by Django 5.2.11 on 2026-05-21 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_scholarshipapplication_decision_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='aspirations',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='fears',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='justification',
            field=models.TextField(blank=True, default='', help_text='Why the student needs assistance'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='plans',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='FundingNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tuition_gap', models.IntegerField(default=0, help_text='Tuition not covered by subsidy (RM)')),
                ('laptop', models.IntegerField(default=0)),
                ('hostel', models.IntegerField(default=0)),
                ('transport', models.IntegerField(default=0)),
                ('books', models.IntegerField(default=0)),
                ('monthly_allowance', models.IntegerField(default=0, help_text='Living allowance per month (RM)')),
                ('allowance_months', models.IntegerField(default=0, help_text='Number of months of allowance')),
                ('other', models.IntegerField(default=0)),
                ('other_desc', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_need', to='scholarship.scholarshipapplication')),
            ],
            options={
                'db_table': 'funding_needs',
            },
        ),
    ]
