# Generated by Django 5.2.11 on 2026-05-21 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0003_scholarshipapplication_aspirations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('ic', 'Identity Card'), ('results_slip', 'Results Slip'), ('photo', 'Photo'), ('epf', 'EPF Statement'), ('str', 'STR Document'), ('statement_of_intent', 'Statement of Intent'), ('reference_letter', 'Reference Letter')], max_length=30)),
                ('storage_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='scholarship.scholarshipapplication')),
            ],
            options={
                'db_table': 'applicant_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(default='share_with_sponsors', max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('locale', models.CharField(default='en', max_length=2)),
                ('granted_by', models.CharField(choices=[('self', 'Self'), ('guardian', 'Guardian')], default='self', max_length=20)),
                ('guardian_name', models.CharField(blank=True, default='', max_length=200)),
                ('guardian_relationship', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='scholarship.scholarshipapplication')),
            ],
            options={
                'db_table': 'consents',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='', help_text='e.g. teacher, school counsellor, referring org contact', max_length=200)),
                ('relationship', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referees', to='scholarship.scholarshipapplication')),
            ],
            options={
                'db_table': 'referees',
            },
        ),
    ]
