# Generated by Django 5.2.11 on 2026-05-21 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0004_applicantdocument_consent_referee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_markdown', models.TextField(blank=True, default='')),
                ('edited_markdown', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=20)),
                ('model_used', models.CharField(blank=True, default='', max_length=50)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_profile', to='scholarship.scholarshipapplication')),
            ],
            options={
                'db_table': 'sponsor_profiles',
            },
        ),
    ]
