# Generated by Django 5.2.11 on 2026-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0005_sponsorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='household_income',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='household_size',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='receives_jkm',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='receives_str',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='spm_a_count',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='stpm_pngk',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='intake_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='Immutable record of what the applicant declared at submit time (profile + application fields). Audit evidence, NOT the live source.'),
        ),
    ]
