# Generated by Django 5.2.11 on 2026-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0006_remove_scholarshipapplication_household_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='anything_else',
            field=models.TextField(blank=True, default='', help_text="'Anything else you'd like us to know' — narrative context only"),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='field_of_study',
            field=models.CharField(blank=True, default='', help_text='Intended field of study (taxonomy key/label)', max_length=50),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='help_scholarship',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Not sure')], default='', help_text='Wants help with scholarship applications & interviews', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='help_university',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Not sure')], default='', help_text='Wants help with university applications', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='mentoring_candidate',
            field=models.BooleanField(default=False, help_text='Flagged for mentoring (lost/unfocused); coordinator-facing, NOT a reject signal'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='other_scholarships',
            field=models.JSONField(blank=True, default=list, help_text="Other scholarships applied/held (keys): ['jpa','petronas','mara',...]"),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='other_scholarships_text',
            field=models.CharField(blank=True, default='', help_text='Other scholarships not in the list (free text)', max_length=300),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='pathways_considered',
            field=models.JSONField(blank=True, default=list, help_text="Post-SPM pathways being considered (non-exclusive): ['matrik','asasi','stpm','poly','kkom',...]"),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='top_choices',
            field=models.JSONField(blank=True, default=list, help_text='Ranked top-3 choices: [{rank, course_id, course_name, institution}]'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='upu_status',
            field=models.CharField(blank=True, choices=[('applied', 'Applied through UPU'), ('public_other', 'Plan STPM / Matrikulasi / PISMP / TVET'), ('ipts', 'Plan to study at IPTS'), ('unknown', 'Unsure what UPU is')], default='', help_text="UPU / destination intent; 'ipts'-only is a disqualifier (S8)", max_length=20),
        ),
    ]
