# Generated by Django 5.2.11 on 2026-05-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0007_scholarshipapplication_anything_else_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='decision_due_at',
            field=models.DateTimeField(blank=True, help_text='When the verdict is revealed (submit + success/decline delay)', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='decision_released_at',
            field=models.DateTimeField(blank=True, help_text='When the scheduler flipped status + sent the verdict email', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='verdict',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='', help_text="Engine's computed outcome ('shortlisted'/'rejected'), stored at submit; status stays 'submitted' until the scheduler releases it", max_length=20),
        ),
        migrations.AddField(
            model_name='scholarshipcohort',
            name='decline_delay_hours',
            field=models.IntegerField(default=48, help_text='Hours after submit before the warm decline email (S8 delayed reveal)'),
        ),
        migrations.AddField(
            model_name='scholarshipcohort',
            name='min_spm_bplus_count',
            field=models.IntegerField(default=5, help_text="Minimum SPM grades at B+ or better (the '+1 B+' beyond the A's → 5 strong subjects)"),
        ),
        migrations.AddField(
            model_name='scholarshipcohort',
            name='per_capita_ceiling',
            field=models.IntegerField(default=1584, help_text='Per-capita monthly income ceiling in RM for non-STR applicants (household_income / household_size). RM5,860 B40 ceiling / 3.7 avg household = RM1,584 (DOSM 2024).'),
        ),
        migrations.AddField(
            model_name='scholarshipcohort',
            name='success_delay_hours',
            field=models.IntegerField(default=2, help_text='Hours after submit before the shortlist (invitation) email + follow-up unlock (S8 delayed reveal)'),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='bucket_b_margin',
            field=models.IntegerField(default=1, help_text='DEPRECATED (pre-S8 marginal-miss logic); unused by the current engine'),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='fail_email_delay_days',
            field=models.IntegerField(default=3, help_text='DEPRECATED (pre-S8); the scheduler now uses success/decline_delay_hours'),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='income_ceiling',
            field=models.IntegerField(blank=True, help_text='B40 monthly household income ceiling in RM (reference; the income gate uses per_capita_ceiling)', null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='min_spm_a_count',
            field=models.IntegerField(default=4, help_text='Minimum SPM grades at A- or better (A+/A/A- all count)'),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='min_stpm_pngk',
            field=models.FloatField(default=2.9, help_text='Minimum STPM PNGK (academic floor)'),
        ),
    ]
