# Generated by Django 5.2.11 on 2026-05-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0009_scholarshipapplication_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='chosen_pathway',
            field=models.CharField(blank=True, default='', help_text="When sure: the pathway_type (matric/stpm/asasi/university/poly/kkom/pismp/iljtm/ilkbs), or 'ipts'/'none' (→ upu_status='ipts').", max_length=20),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='chosen_programme',
            field=models.JSONField(blank=True, default=dict, help_text='Single chosen programme when sure: {course_id, course_name, institution, source}.'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='pathway_certainty',
            field=models.CharField(blank=True, choices=[('sure', 'Knows pathway'), ('uncertain', 'Still deciding')], default='', help_text='Top split: does the student already know their pathway?', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='pre_u_institution',
            field=models.CharField(blank=True, default='', help_text='Chosen STPM school or Matriculation college name.', max_length=255),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='pre_u_track',
            field=models.CharField(blank=True, default='', help_text='STPM bidang (sains/sains_sosial/not_sure) or Matric track (sains/kejuruteraan/sains_komputer/perakaunan).', max_length=30),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='uncertainty_note',
            field=models.TextField(blank=True, default='', help_text="When uncertain: 'where are you right now?' free text (Plans step)."),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='uncertainty_reasons',
            field=models.JSONField(blank=True, default=list, help_text="When uncertain: reason keys ['waiting','guidance','financial','family','appeal','other']."),
        ),
    ]
