# Generated by Django 5.2.11 on 2026-05-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0010_plans_redesign_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='declaration_name',
            field=models.CharField(blank=True, default='', help_text='Full name typed by the student as their signature on the truthfulness declaration', max_length=200),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='declared_at',
            field=models.DateTimeField(blank=True, help_text='When the student signed the truthfulness declaration (at submit)', null=True),
        ),
    ]
