# Generated by Django 5.2.11 on 2026-05-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0011_scholarshipapplication_declaration_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='daily_life',
            field=models.TextField(blank=True, default='', help_text='What is your daily life like? Any responsibilities such as work or caring for family?'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='family_context',
            field=models.TextField(blank=True, default='', help_text="Anything about your family's situation we should know?"),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='first_in_family',
            field=models.BooleanField(default=False, help_text='I would be the first in my family to go to university.'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='parents_occupation',
            field=models.CharField(blank=True, default='', help_text='What do your parents or guardians do for a living?', max_length=255),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='siblings_studying',
            field=models.BooleanField(default=False, help_text='One or more of my siblings are also studying.'),
        ),
    ]
