# Generated by Django 5.2.11 on 2026-05-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0012_story_narrative_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingneed',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='Selected support categories: living/transport/accommodation/books/device/tuition/other'),
        ),
        migrations.AddField(
            model_name='fundingneed',
            name='funding_note',
            field=models.TextField(blank=True, default='', help_text="Open: how they'd use it / plan to fund studies / cope without"),
        ),
        migrations.AddField(
            model_name='fundingneed',
            name='programme_months',
            field=models.IntegerField(blank=True, help_text='Programme length in months', null=True),
        ),
    ]
