# Generated by Django 5.2.11 on 2026-05-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0021_consent_guardian_nric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='siblings_studying',
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='siblings_studying_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text="How many of the applicant's siblings are currently studying. A proxy for how much education-funding burden the family carries.", null=True),
        ),
    ]
