# Generated by Django 5.2.11 on 2026-05-29 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_partneradmin_role'),
        ('scholarship', '0022_remove_scholarshipapplication_siblings_studying_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Phase C: the reviewer assigned to interview this applicant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to='courses.partneradmin'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='info_request_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='info_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='verdict',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='', help_text="Engine's computed outcome ('shortlisted'/'rejected'), stored at submit; status stays 'submitted' until the scheduler releases it", max_length=20),
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=20)),
                ('findings', models.JSONField(blank=True, default=dict)),
                ('rubric', models.JSONField(blank=True, default=dict)),
                ('overall_note', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='scholarship.scholarshipapplication')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to='courses.partneradmin')),
            ],
            options={
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
