# Generated by Django 5.2.11 on 2026-05-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0023_scholarshipapplication_assigned_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sponsor_interests',
                'ordering': ['-created_at'],
            },
        ),
    ]
