# Generated by Django 5.2.11 on 2026-05-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0024_sponsorinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocument',
            name='vision_address_match',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='vision_name_match',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
