# Generated by Django 5.2.11 on 2026-05-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0025_applicantdocument_vision_address_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocument',
            name='vision_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='applicantdocument',
            name='vision_fields_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
