# Generated by Django 5.2.11 on 2026-05-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0026_applicantdocument_vision_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_gaps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_gaps_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
