# Generated by Django 5.2.11 on 2026-05-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0027_scholarshipapplication_interview_gaps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='final_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='final_model_used',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='finalised_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
