# Generated by Django 5.2.11 on 2026-05-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0028_sponsorprofile_final_markdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='rejected_by',
            field=models.CharField(blank=True, default='', help_text='Email of the PartnerAdmin who rejected (post-shortlist buckets only); blank for engine rejections', max_length=254),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('merit', 'Did not meet the academic/merit floor'), ('need', 'Did not meet the financial-need criteria'), ('ineligible', 'Out of scope / ineligible'), ('interview', 'Reviewed but not selected'), ('contractual', 'Failed post-award contractual steps')], default='', help_text="Why the application was rejected; blank unless status='rejected'", max_length=20),
        ),
    ]
