# Generated by Django 5.2.11 on 2026-05-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0029_scholarshipapplication_rejected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='decline_delay_hours',
            field=models.FloatField(default=48, help_text='Hours after submit before the warm decline email (S8 delayed reveal). Float (see above).'),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='success_delay_hours',
            field=models.FloatField(default=48, help_text='Hours after submit before the shortlist (invitation) email + follow-up unlock (S8 delayed reveal). Float so sub-hour delays are possible (e.g. 0.9167 = 55 minutes).'),
        ),
    ]
