# Generated by Django 5.2.11 on 2026-05-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0030_alter_scholarshipcohort_decline_delay_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.CharField(help_text='Supabase Auth UID, set when the sponsor self-registers', max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('organisation', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, default='', help_text='Email of the PartnerAdmin who vetted this sponsor', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sponsors',
                'ordering': ['-created_at'],
            },
        ),
    ]
