# Generated by Django 5.2.11 on 2026-05-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0031_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='consent_version',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
