# Generated by Django 5.2.11 on 2026-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0032_sponsor_contact_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorprofile',
            name='anon_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='anon_markdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='anon_model_used',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='anon_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='anon_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
