# Generated by Django 5.2.11 on 2026-05-31 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0033_sponsor_pool_anon_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='award_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('sponsored', 'Sponsored'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='verdict',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('sponsored', 'Sponsored'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='', help_text="Engine's computed outcome ('shortlisted'/'rejected'), stored at submit; status stays 'submitted' until the scheduler releases it", max_length=20),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, default='mock', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='scholarship.sponsor')),
            ],
            options={
                'db_table': 'sponsor_donations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('active', 'Active'), ('lapsed', 'Lapsed'), ('cancelled', 'Cancelled')], default='offered', max_length=20)),
                ('accept_deadline', models.DateTimeField(blank=True, null=True)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='scholarship.scholarshipapplication')),
                ('consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scholarship.consent')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='scholarship.sponsor')),
            ],
            options={
                'db_table': 'sponsorships',
                'ordering': ['-offered_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['offered', 'active'])), fields=('application',), name='uniq_holding_sponsorship_per_app')],
            },
        ),
    ]
