# Generated by Django 5.2.11 on 2026-06-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0034_sponsorship_donation_award'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorInterest',
        ),
    ]
