# Generated by Django 5.2.11 on 2026-06-01 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0035_remove_sponsor_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.CharField(default='other', max_length=20)),
                ('code', models.CharField(max_length=60)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('prompt', models.TextField(blank=True, default='', help_text='Officer-written ask (officer items); system items resolve copy from code via i18n.')),
                ('kind', models.CharField(choices=[('doc', 'Upload a document'), ('confirm', 'Confirm / correct a value'), ('explanation', 'Explain in your own words')], default='doc', max_length=20)),
                ('doc_type', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('waived', 'Waived')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('system', 'System'), ('officer', 'Officer')], default='system', max_length=20)),
                ('resolution_text', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', help_text="Email of the PartnerAdmin for officer items; '' for system items.", max_length=254)),
                ('resolved_by', models.CharField(blank=True, default='', help_text="'student' / 'system' / a PartnerAdmin email.", max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_items', to='scholarship.scholarshipapplication')),
                ('resolution_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolves_items', to='scholarship.applicantdocument')),
            ],
            options={
                'db_table': 'resolution_items',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source', 'system')), fields=('application', 'code'), name='uniq_system_resolution_per_code')],
            },
        ),
    ]
