# Generated by Django 5.2.11 on 2026-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0037_verdict_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='pathway_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
