# Generated by Django 5.2.11 on 2026-06-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0038_pathway_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='earner_work_status',
            field=models.CharField(blank=True, choices=[('', 'Not chosen'), ('payslip', 'Working — has payslip'), ('informal', 'Working — no payslip'), ('not_working', 'Not working')], default='', help_text='Wizard Q3 (salary route): payslip→salary slip+EPF, not_working→EPF only, informal→utility bills + officer judgement (never blocked).', max_length=12),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='household_other_earners',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Wizard Q4 (non-STR): other working household members (e.g. a working sibling). Guards against an under-declared household income.', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='income_earner',
            field=models.CharField(blank=True, choices=[('', 'Not chosen'), ('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal guardian')], default='', help_text='Wizard Q2 whose income is shown — drives the relationship proof: father=student-IC patronymic, mother=birth_certificate, guardian=guardianship_letter.', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='income_route',
            field=models.CharField(blank=True, choices=[('', 'Not chosen'), ('str', 'STR'), ('salary', 'Salary')], default='', help_text="Wizard Q1 'have an STR document?': yes→'str' route, no→'salary' route.", max_length=10),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='siblings_in_school',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Family burden: dependents (siblings) currently in school.', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='siblings_in_tertiary',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Family burden: dependents (siblings) in pre-U / college / university.', null=True),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='doc_type',
            field=models.CharField(choices=[('ic', 'Identity Card'), ('results_slip', 'Results Slip'), ('photo', 'Photo'), ('epf', 'EPF Statement'), ('str', 'STR Document'), ('statement_of_intent', 'Statement of Intent'), ('reference_letter', 'Reference Letter'), ('salary_slip', 'Salary Slip'), ('water_bill', 'Water Bill'), ('electricity_bill', 'Electricity Bill'), ('offer_letter', 'Offer Letter'), ('parent_ic', 'Parent/Guardian IC'), ('guardianship_letter', 'Guardianship Letter'), ('birth_certificate', 'Birth Certificate')], max_length=30),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='siblings_studying_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text="How many of the applicant's siblings are currently studying. A proxy for how much education-funding burden the family carries. Kept for back-compat; the income wizard now splits this into school + tertiary below (the sum = studying).", null=True),
        ),
    ]
