# Generated by Django 5.2.11 on 2026-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0039_scholarshipapplication_earner_work_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocument',
            name='household_member',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal guardian'), ('brother', 'Elder brother'), ('sister', 'Elder sister')], default='', help_text='Salary-route income docs only — whose IC/salary slip/EPF this is. Blank for all other documents.', max_length=10),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='income_working_members',
            field=models.JSONField(blank=True, default=list, help_text='Salary route: household members who work (subset of father/mother/guardian/brother/sister). Drives per-member income docs.'),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='earner_work_status',
            field=models.CharField(blank=True, choices=[('', 'Not chosen'), ('payslip', 'Working — has payslip'), ('informal', 'Working — no payslip'), ('not_working', 'Not working')], default='', help_text='DEPRECATED (salary route) — informal is now inferred. STR route unaffected.', max_length=12),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='household_other_earners',
            field=models.PositiveSmallIntegerField(blank=True, help_text='DEPRECATED — superseded by income_working_members (siblings ticked explicitly).', null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='income_earner',
            field=models.CharField(blank=True, choices=[('', 'Not chosen'), ('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Legal guardian')], default='', help_text='STR route only — whose income/STR is shown (single earner). Drives the relationship proof: father=student-IC patronymic, mother=birth_certificate, guardian=guardianship_letter. The SALARY route uses income_working_members (multi-select) instead.', max_length=10),
        ),
    ]
