# Generated by Django 5.2.11 on 2026-06-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_studentprofile_elective_subjects'),
        ('scholarship', '0040_applicantdocument_household_member_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scholarshipapplication',
            name='unique_application_per_cohort',
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='reminder_anchor_at',
            field=models.DateTimeField(blank=True, help_text='When the completion-reminder clock starts (usually = shortlisted_at)', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='reminder_stage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('sponsored', 'Sponsored'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired (not completed in time)')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='verdict',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('sponsored', 'Sponsored'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired (not completed in time)')], default='', help_text="Engine's computed outcome ('shortlisted'/'rejected'), stored at submit; status stays 'submitted' until the scheduler releases it", max_length=20),
        ),
        migrations.AddConstraint(
            model_name='scholarshipapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('profile__isnull', False), models.Q(('status', 'expired'), _negated=True)), fields=('cohort', 'profile'), name='unique_application_per_cohort'),
        ),
    ]
