# Generated by Django 5.2.11 on 2026-06-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0043_backfill_sibling_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolutionitem',
            name='kind',
            field=models.CharField(choices=[('doc', 'Upload a document'), ('confirm', 'Confirm / correct a value'), ('explanation', 'Explain in your own words'), ('clarify', 'Answer a question'), ('human', 'For the reviewer')], default='doc', max_length=20),
        ),
        migrations.AlterField(
            model_name='resolutionitem',
            name='source',
            field=models.CharField(choices=[('system', 'System'), ('officer', 'Officer'), ('check2', 'Check 2')], default='system', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='resolutionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'check2')), fields=('application', 'code'), name='uniq_check2_resolution_per_code'),
        ),
    ]
