# Generated by Django 5.2.11 on 2026-06-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0045_check2_query_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='query_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipcohort',
            name='query_response_sla_days',
            field=models.PositiveSmallIntegerField(default=5, help_text='Check-2 query SLA: days after submit to answer clarify queries before the application is ready for assignment regardless (proceed-as-is, flagged).'),
        ),
    ]
