# Generated by Django 5.2.11 on 2026-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0046_check2_sla_clock'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='query_raised_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
