# Generated by Django 5.2.11 on 2026-06-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0047_check2_query_raised_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='father_name',
            field=models.CharField(blank=True, default='', help_text="Father's name as in IC (structured roster).", max_length=200),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='father_occupation',
            field=models.CharField(blank=True, choices=[('gov', 'Government / civil servant'), ('professional', 'Professional / executive (engineer, accountant, manager)'), ('teacher', 'Teacher / educator'), ('uniform', 'Armed forces / police'), ('healthcare', 'Nurse / healthcare staff'), ('factory', 'Factory / production operator'), ('technician', 'Technician (electrical / IT / machinery)'), ('clerk', 'Office / admin / clerk'), ('private', 'Private company employee (general)'), ('retail', 'Cashier / sales assistant'), ('storekeeper', 'Store clerk / shop / warehouse worker'), ('fnb', 'Food & beverage / restaurant staff'), ('security', 'Security guard'), ('cleaner', 'Cleaner / general worker'), ('maintenance', 'Maintenance / repair (handyman, plumber, electrician)'), ('plantation', 'Plantation / estate worker'), ('hawker', 'Small trader / stall / hawker'), ('farmer', 'Farmer (paddy / vegetables)'), ('smallholder', 'Smallholder (rubber / oil palm)'), ('fisherman', 'Fisherman'), ('livestock', 'Livestock / poultry'), ('ehailing', 'E-hailing / delivery rider'), ('driver', 'Driver (taxi / bus / lorry)'), ('construction', 'Construction / labourer'), ('supervisor', 'Supervisor / foreman'), ('mechanic', 'Mechanic / workshop'), ('craft', 'Tailor / craft / home business'), ('hairdresser', 'Hairdresser / beauty / personal care'), ('tuition', 'Tuition / freelance teacher'), ('caregiver', 'Caregiver / domestic helper'), ('agent', 'Insurance / sales agent'), ('odd_jobs', 'Odd jobs / daily wage'), ('self_employed', 'Self-employed / freelance'), ('homemaker', 'Homemaker'), ('retired', 'Retired / pensioner'), ('unemployed', 'Unemployed'), ('unable', 'Unable to work (illness / disability)'), ('deceased', 'Passed away'), ('no_contact', 'Not in contact'), ('other', 'Other')], default='', help_text="Father's profession (coded; see family.PROFESSION_CHOICES).", max_length=40),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='father_occupation_other',
            field=models.CharField(blank=True, default='', help_text="Father's profession free text when occupation == 'other'.", max_length=120),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='mother_name',
            field=models.CharField(blank=True, default='', help_text="Mother's name as in IC (structured roster).", max_length=200),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='mother_occupation',
            field=models.CharField(blank=True, choices=[('gov', 'Government / civil servant'), ('professional', 'Professional / executive (engineer, accountant, manager)'), ('teacher', 'Teacher / educator'), ('uniform', 'Armed forces / police'), ('healthcare', 'Nurse / healthcare staff'), ('factory', 'Factory / production operator'), ('technician', 'Technician (electrical / IT / machinery)'), ('clerk', 'Office / admin / clerk'), ('private', 'Private company employee (general)'), ('retail', 'Cashier / sales assistant'), ('storekeeper', 'Store clerk / shop / warehouse worker'), ('fnb', 'Food & beverage / restaurant staff'), ('security', 'Security guard'), ('cleaner', 'Cleaner / general worker'), ('maintenance', 'Maintenance / repair (handyman, plumber, electrician)'), ('plantation', 'Plantation / estate worker'), ('hawker', 'Small trader / stall / hawker'), ('farmer', 'Farmer (paddy / vegetables)'), ('smallholder', 'Smallholder (rubber / oil palm)'), ('fisherman', 'Fisherman'), ('livestock', 'Livestock / poultry'), ('ehailing', 'E-hailing / delivery rider'), ('driver', 'Driver (taxi / bus / lorry)'), ('construction', 'Construction / labourer'), ('supervisor', 'Supervisor / foreman'), ('mechanic', 'Mechanic / workshop'), ('craft', 'Tailor / craft / home business'), ('hairdresser', 'Hairdresser / beauty / personal care'), ('tuition', 'Tuition / freelance teacher'), ('caregiver', 'Caregiver / domestic helper'), ('agent', 'Insurance / sales agent'), ('odd_jobs', 'Odd jobs / daily wage'), ('self_employed', 'Self-employed / freelance'), ('homemaker', 'Homemaker'), ('retired', 'Retired / pensioner'), ('unemployed', 'Unemployed'), ('unable', 'Unable to work (illness / disability)'), ('deceased', 'Passed away'), ('no_contact', 'Not in contact'), ('other', 'Other')], default='', help_text="Mother's profession (coded).", max_length=40),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='mother_occupation_other',
            field=models.CharField(blank=True, default='', help_text="Mother's profession free text when occupation == 'other'.", max_length=120),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='other_family_members',
            field=models.JSONField(blank=True, default=list, help_text='Optional pool: [{role: brother|sister|guardian, occupation: <code>, occupation_other: <str>}] — extra family members + their professions.'),
        ),
    ]
