# Generated by Django 5.2.11 on 2026-06-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0049_f8a_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='last_digest_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='notify_frequency',
            field=models.CharField(choices=[('realtime', 'Real-time'), ('weekly', 'Weekly digest'), ('off', 'Off')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='sponsorprofile',
            name='realtime_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
