# Generated by Django 5.2.11 on 2026-06-09 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_studentprofile_elective_subjects'),
        ('scholarship', '0050_f3_sponsor_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(blank=True, default='', max_length=120)),
                ('university', models.CharField(blank=True, default='', max_length=200)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('field_of_study', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to='courses.partneradmin')),
            ],
            options={
                'db_table': 'reviewer_profiles',
            },
        ),
    ]
