# Generated by Django 5.2.11 on 2026-06-09 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_studentprofile_elective_subjects'),
        ('scholarship', '0051_reviewerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='F7: when the current reviewer was assigned (null = unassigned)', null=True),
        ),
        migrations.CreateModel(
            name='AssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by_email', models.CharField(blank=True, default='', help_text='Email of the super-admin who performed the (re)assignment.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_events', to='scholarship.scholarshipapplication')),
                ('from_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.partneradmin')),
                ('to_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.partneradmin')),
            ],
            options={
                'db_table': 'assignment_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
