# Generated by Django 5.2.11 on 2026-06-09 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0052_scholarshipapplication_assigned_at_assignmentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('scrubbed_text', models.TextField(blank=True, default='')),
                ('scan_result', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('blocked', 'Blocked — identifiers'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_by', models.CharField(blank=True, default='', max_length=254)),
                ('review_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_messages', to='scholarship.scholarshipapplication')),
            ],
            options={
                'db_table': 'graduation_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, default='', max_length=50)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('graduated', models.BooleanField(default=False, help_text="True when this result marks the student's graduation.")),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='scholarship.scholarshipapplication')),
                ('results_slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scholarship.applicantdocument')),
            ],
            options={
                'db_table': 'semester_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
