# Generated by Django 5.2.11 on 2026-06-09 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0053_graduationmessage_semesterresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(blank=True, default='', max_length=254)),
                ('invitee_name', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('expired', 'Expired')], default='invited', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='scholarship.sponsor')),
                ('registered_sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scholarship.sponsor')),
            ],
            options={
                'db_table': 'sponsor_referrals',
                'ordering': ['-created_at'],
            },
        ),
    ]
