# Generated by Django 5.2.11 on 2026-06-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0054_sponsorreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reviewerprofile',
            name='street_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
