# Generated by Django 5.2.11 on 2026-06-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0055_reviewerprofile_city_reviewerprofile_postcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='income_ceiling',
            field=models.IntegerField(blank=True, help_text='B40 monthly household GROSS income ceiling in RM (DOSM B40 line, RM5,860 in 2024). PRIMARY income gate: a non-STR applicant at or below this passes regardless of household size.', null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='per_capita_ceiling',
            field=models.IntegerField(default=1584, help_text='Per-capita monthly income ceiling in RM (household_income / household_size). SAFETY NET only — applies to non-STR applicants whose gross income is ABOVE income_ceiling, rescuing large households. RM5,860 B40 ceiling / 3.7 avg household = RM1,584 (DOSM 2024).'),
        ),
    ]
