# Generated by Django 5.2.11 on 2026-06-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0056_alter_scholarshipcohort_income_ceiling_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='doc_type',
            field=models.CharField(choices=[('ic', 'Identity Card'), ('results_slip', 'Results Slip'), ('photo', 'Photo'), ('epf', 'EPF Statement'), ('str', 'STR Document'), ('statement_of_intent', 'Statement of Intent'), ('reference_letter', 'Reference Letter'), ('salary_slip', 'Salary Slip'), ('water_bill', 'Water Bill'), ('electricity_bill', 'Electricity Bill'), ('offer_letter', 'Offer Letter'), ('parent_ic', 'Parent/Guardian IC'), ('guardianship_letter', 'Guardianship Letter'), ('birth_certificate', 'Birth Certificate'), ('other', 'Other Document')], max_length=30),
        ),
    ]
