# Generated by Django 5.2.11 on 2026-06-17 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0057_studentprofile_chosen_pathway_and_more'),
        ('scholarship', '0060_reviewerprofile_share_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_calendar_event_id',
            field=models.CharField(blank=True, default='', help_text='Google Calendar event id, so the booking can be updated/cancelled.', max_length=255),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_confirmation_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_meeting_provider',
            field=models.CharField(blank=True, default='', help_text="'google_meet' (auto-generated) or 'manual' (pasted by an admin).", max_length=20),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_meeting_url',
            field=models.URLField(blank=True, default='', help_text='Google Meet (or manually-pasted) join link for the booked interview.'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_reminded_1d_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_reminded_1h_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_start',
            field=models.DateTimeField(blank=True, help_text="Denormalised start of the booked interview (the chosen slot's time).", null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_status',
            field=models.CharField(blank=True, choices=[('', 'Not booked'), ('booked', 'Booked'), ('cancelled', 'Cancelled')], default='', max_length=10),
        ),
        migrations.CreateModel(
            name='InterviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Proposed interview start (tz-aware).')),
                ('duration_min', models.PositiveSmallIntegerField(default=45)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_slots', to='scholarship.scholarshipapplication')),
                ('reviewer', models.ForeignKey(help_text='The reviewer who proposed this slot (= the assigned reviewer).', on_delete=django.db.models.deletion.CASCADE, related_name='proposed_interview_slots', to='courses.partneradmin')),
            ],
            options={
                'db_table': 'interview_slots',
                'ordering': ['start'],
            },
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_slot',
            field=models.ForeignKey(blank=True, help_text='The proposed slot the student booked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scholarship.interviewslot'),
        ),
    ]
