# Generated by Django 5.2.11 on 2026-06-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0066_standinggift'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(blank=True, default='', max_length=50)),
                ('to_number', models.CharField(blank=True, default='', max_length=32)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('undelivered', 'Undelivered')], default='queued', max_length=20)),
                ('provider_sid', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='scholarship.scholarshipapplication')),
            ],
            options={
                'db_table': 'whatsapp_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
