# Generated by Django 5.2.11 on 2026-06-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0066_standinggift'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdocument',
            name='request_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
