# Generated by Django 5.2.11 on 2026-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0068_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='award_due_at',
            field=models.DateTimeField(blank=True, help_text='When a pending award confirmation finalises (cool-off end)', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='decline_due_at',
            field=models.DateTimeField(blank=True, help_text='When a pending decline reveals + emails (cool-off end)', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='pending_decline_by',
            field=models.CharField(blank=True, default='', help_text='Email of the admin who scheduled the pending decline', max_length=254),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='pending_rejection_category',
            field=models.CharField(blank=True, choices=[('merit', 'Did not meet the academic/merit floor'), ('need', 'Did not meet the financial-need criteria'), ('ineligible', 'Out of scope / ineligible'), ('interview', 'Reviewed but not selected'), ('contractual', 'Failed post-award contractual steps')], default='', help_text='A scheduled-but-unrevealed decline bucket (cool-off); blank = none pending', max_length=20),
        ),
    ]
