# Generated by Django 5.2.11 on 2026-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0069_decline_award_cooloff'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='interview_cancel_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
