# Generated by Django 5.2.11 on 2026-06-26 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_studentprofile_whatsapp_opt_in'),
        ('scholarship', '0071_sponsorprofile_anon_blurb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BursaryAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('locale', models.CharField(default='en', max_length=5)),
                ('award_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('payment_schedule', models.TextField(blank=True, default='')),
                ('institution_name', models.CharField(blank=True, default='', max_length=255)),
                ('course_name', models.CharField(blank=True, default='', max_length=255)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('progress_standard', models.TextField(blank=True, default='')),
                ('foundation_signatory_name', models.CharField(blank=True, default='', max_length=200)),
                ('foundation_signatory_title', models.CharField(blank=True, default='', max_length=255)),
                ('foundation_signatory_nric', models.CharField(blank=True, default='', max_length=20)),
                ('student_signed_name', models.CharField(blank=True, default='', max_length=200)),
                ('student_signed_nric', models.CharField(blank=True, default='', max_length=20)),
                ('student_signed_at', models.DateTimeField(blank=True, null=True)),
                ('student_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('guarantor_name', models.CharField(blank=True, default='', max_length=200)),
                ('guarantor_nric', models.CharField(blank=True, default='', max_length=20)),
                ('guarantor_relationship', models.CharField(blank=True, default='', max_length=50)),
                ('guarantor_method', models.CharField(default='in_session', max_length=20)),
                ('guarantor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('guarantor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('foundation_signed_by', models.CharField(blank=True, default='', max_length=200)),
                ('foundation_signed_at', models.DateTimeField(blank=True, null=True)),
                ('witness_signed_by', models.CharField(blank=True, default='', max_length=200)),
                ('witness_name', models.CharField(blank=True, default='', max_length=200)),
                ('witness_signed_at', models.DateTimeField(blank=True, null=True)),
                ('rendered_html', models.TextField(blank=True, default='')),
                ('agreement_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('pdf_storage_path', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bursary_agreement', to='scholarship.scholarshipapplication')),
                ('sponsorship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scholarship.sponsorship')),
                ('witness_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'bursary_agreements',
                'ordering': ['-created_at'],
            },
        ),
    ]
