# Generated by Django 5.2.15 on 2026-06-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0072_bursaryagreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('recommended', 'Recommended'), ('accepted', 'Accepted'), ('sponsored', 'Sponsored'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired (not completed in time)')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='verdict',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('recommended', 'Recommended'), ('accepted', 'Accepted'), ('sponsored', 'Sponsored'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired (not completed in time)')], default='', help_text="Engine's computed outcome ('shortlisted'/'rejected'), stored at submit; status stays 'submitted' until the scheduler releases it", max_length=20),
        ),
        # NB: choices are app-level only — this migration makes NO DDL change (the column is already
        # varchar(20)). It is state-only; applying it on prod = recording the django_migrations row.
        # The data move (UPDATE status='accepted'->'recommended', ~23 rows) is a separate deploy step.
    ]
