# Generated by Django 5.2.15 on 2026-06-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0073_alter_scholarshipapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('graduated', 'Graduated — completed the programme'), ('completed', 'Completed the contractual support period'), ('withdrawn', 'Withdrawn by the student'), ('lapsed', 'Lapsed — support stopped (fell away)'), ('terminated', 'Terminated for cause')], default='', help_text="Why the application reached status='closed'; blank unless status='closed'", max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('recommended', 'Recommended'), ('awarded', 'Awarded'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('sponsored', 'Sponsored'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired (not completed in time)')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='verdict',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('recommended', 'Recommended'), ('awarded', 'Awarded'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('sponsored', 'Sponsored'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired (not completed in time)')], default='', help_text="Engine's computed outcome ('shortlisted'/'rejected'), stored at submit; status stays 'submitted' until the scheduler releases it", max_length=20),
        ),
        # NB: the `closure_reason` AddField is real additive DDL (apply migrate-first). The two status
        # AlterFields are choices-only (app-level, no DDL). The foreign `ScholarshipCohort.name`
        # help_text drift that makemigrations keeps proposing is deliberately EXCLUDED (not ours).
    ]
