# Generated by Django 5.2.15 on 2026-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0074_scholarshipapplication_closure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('recommended', 'Recommended'), ('awarded', 'Awarded'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired (not completed in time)')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='verdict',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('profile_complete', 'Profile complete'), ('interviewing', 'Interviewing'), ('interviewed', 'Interviewed'), ('recommended', 'Recommended'), ('awarded', 'Awarded'), ('active', 'Active'), ('maintenance', 'Maintenance'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired (not completed in time)')], default='', help_text="Engine's computed outcome ('shortlisted'/'rejected'), stored at submit; status stays 'submitted' until the scheduler releases it", max_length=20),
        ),
        # State-only: choices are app-level (no DDL) — drops 'sponsored' from the enum. The foreign
        # ScholarshipCohort.name help_text drift makemigrations keeps proposing is excluded (not ours).
    ]
