# Generated by Django 5.2.15 on 2026-06-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0078_closure_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='name',
            field=models.CharField(help_text="Display name, e.g. 'BrightPath Bursary Programme 2026'", max_length=200),
        ),
    ]
