# Generated by Django 5.2.15 on 2026-06-29 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0081_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorship',
            name='offer_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
