# Generated by Django 5.2.15 on 2026-06-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0082_sponsorship_offer_emailed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='comprehension_passed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
