# Generated by Django 5.2.15 on 2026-07-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0088_alter_scholarshipapplication_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="The student's message (capped at 1000 chars on write).")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_messages', to='scholarship.scholarshipapplication')),
            ],
            options={
                'db_table': 'interview_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
