# Generated by Django 5.2.15 on 2026-07-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0089_interviewmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='decline_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the bucket decline email was actually sent (distinct from the shortlist decision email stamp)', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='pre_decline_status',
            field=models.CharField(blank=True, default='', help_text="Status snapshot taken at admin_reject; cancel_pending_decline restores to it (blank = legacy row, falls back to 'interviewed')", max_length=20),
        ),
    ]
