# Generated by Django 5.2.15 on 2026-07-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0090_cancel_decline_integrity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='doc_type',
            field=models.CharField(choices=[('ic', 'Identity Card'), ('results_slip', 'Results Slip'), ('photo', 'Photo'), ('epf', 'EPF Statement'), ('str', 'STR Document'), ('statement_of_intent', 'Statement of Intent'), ('reference_letter', 'Reference Letter'), ('salary_slip', 'Salary Slip'), ('income_support_doc', 'Income Support Document'), ('water_bill', 'Water Bill'), ('electricity_bill', 'Electricity Bill'), ('offer_letter', 'Offer Letter'), ('parent_ic', 'Parent/Guardian IC'), ('guardianship_letter', 'Guardianship Letter'), ('birth_certificate', 'Birth Certificate'), ('bank_statement', 'Bank Statement'), ('school_leaving_cert', 'School Leaving Certificate'), ('semester_result', 'Semester Result Slip'), ('other', 'Other Document')], max_length=30),
        ),
    ]
