# Generated by Django 5.2.15 on 2026-07-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0091_v4_academic_doc_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='qc_override_at',
            field=models.DateTimeField(blank=True, help_text='When the QC gap floor was overridden.', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='qc_override_by',
            field=models.CharField(blank=True, default='', help_text='Email of the super-admin who overrode the QC gap floor.', max_length=254),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='qc_override_reason',
            field=models.TextField(blank=True, default='', help_text="The super-admin's recorded reason for accepting past the verdict gap floor."),
        ),
    ]
