# Generated by Django 5.2.15 on 2026-07-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0093_document_version_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='maintenance_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='recommended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
