# Generated by Django 5.2.15 on 2026-07-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0094_lifecycle_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='recommended_by',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
