# Generated by Django 5.2.15 on 2026-07-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_partnerorganisation_brand_colour_and_more'),
        ('scholarship', '0096_status_awaiting_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipcohort',
            name='owning_organisation',
            field=models.ForeignKey(blank=True, help_text='The tenant organisation that OWNS this programme (platform Sprint 1).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_cohorts', to='courses.partnerorganisation'),
        ),
    ]
