# Generated by Django 5.2.15 on 2026-07-14 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_partnerorganisation_brand_colour_and_more'),
        ('scholarship', '0098_seed_brightpath_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='owning_organisation',
            field=models.ForeignKey(blank=True, help_text='Tenant organisation that owns this application (denormalised from cohort.owning_organisation; set in save()).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_applications', to='courses.partnerorganisation'),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='owning_organisation',
            field=models.ForeignKey(blank=True, help_text='The tenant organisation that OWNS this programme (platform Sprint 1). SOURCE OF TRUTH for tenancy. ScholarshipApplication.owning_organisation is a denormalised copy of this, set in the application save(). A future "move a cohort between organisations" flow MUST cascade the new value to every one of that cohort.applications.owning_organisation (there is no DB trigger — the drift guard test asserts they agree).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_cohorts', to='courses.partnerorganisation'),
        ),
    ]
