# Generated by Django 5.2.15 on 2026-07-16 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_partneradmin_org_admin_role'),
        ('scholarship', '0100_backfill_application_owning_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='payment_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='vircle_id',
            field=models.CharField(blank=True, default='', help_text='Vircle eWallet account ID (13 digits, prefix 8000400175).', max_length=30),
        ),
        migrations.CreateModel(
            name='PaymentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='The Vircle payment date; validated >= today at creation.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('admin_signed', 'Admin signed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reference', models.CharField(help_text="e.g. 'PR-2026-08-001'; 'backfill-YYYY-MM-DD' for imports.", max_length=50, unique=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=254)),
                ('admin_signed_name', models.CharField(blank=True, default='', max_length=200)),
                ('admin_signed_email', models.CharField(blank=True, default='', max_length=254)),
                ('admin_signed_at', models.DateTimeField(blank=True, null=True)),
                ('org_admin_signed_name', models.CharField(blank=True, default='', max_length=200)),
                ('org_admin_signed_email', models.CharField(blank=True, default='', max_length=254)),
                ('org_admin_signed_at', models.DateTimeField(blank=True, null=True)),
                ('drive_file_url', models.URLField(blank=True, default='')),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_runs', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'payment_runs',
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included', models.BooleanField(default=True)),
                ('exclude_reason', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_applied', models.DecimalField(decimal_places=2, default=0, help_text='How much payment_credit this item consumed (audit; decremented at completion).', max_digits=10)),
                ('award_amount_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_to_date_snapshot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vircle_id_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_run_items', to='scholarship.scholarshipapplication')),
                ('disbursement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_run_items', to='scholarship.disbursement')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='scholarship.paymentrun')),
            ],
            options={
                'db_table': 'payment_run_items',
                'ordering': ['id'],
                'unique_together': {('run', 'application')},
            },
        ),
    ]
