# Generated by Django 5.2.15 on 2026-07-18 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_partneradmin_org_admin_role'),
        ('scholarship', '0102_paymentrun_period_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='bursaryagreement',
            name='drive_file_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bursaryagreement',
            name='executed_pdf_emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_deployment', 'Pending deployment'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('title_ms', models.CharField(blank=True, default='', max_length=255)),
                ('title_ta', models.CharField(blank=True, default='', max_length=255)),
                ('preamble_en', models.TextField(blank=True, default='')),
                ('preamble_ms', models.TextField(blank=True, default='')),
                ('preamble_ta', models.TextField(blank=True, default='')),
                ('progress_standard_en', models.TextField(blank=True, default='')),
                ('progress_standard_ms', models.TextField(blank=True, default='')),
                ('progress_standard_ta', models.TextField(blank=True, default='')),
                ('counterparty_name', models.CharField(blank=True, default='', max_length=200)),
                ('counterparty_title', models.CharField(blank=True, default='', max_length=255)),
                ('counterparty_nric', models.CharField(blank=True, default='', max_length=20)),
                ('counterparty_notify_emails', models.JSONField(blank=True, default=list)),
                ('parent_role', models.CharField(choices=[('co_signer_all', 'Co-signer (all students)'), ('minor_only', 'Co-signer (minors only)')], default='co_signer_all', max_length=20)),
                ('parent_pin_required', models.BooleanField(default=True)),
                ('witness_policy', models.CharField(choices=[('none', 'No witness'), ('optional', 'Witness optional'), ('required', 'Witness required')], default='optional', max_length=10)),
                ('vetted_by_name', models.CharField(blank=True, default='', max_length=200)),
                ('vetted_on', models.DateField(blank=True, null=True)),
                ('vetting_attested_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('vetting_attested_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('submitted_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('submitted_by_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('deployed_by_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_templates', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'contract_templates',
                'ordering': ['organisation_id', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('heading_en', models.CharField(blank=True, default='', max_length=255)),
                ('heading_ms', models.CharField(blank=True, default='', max_length=255)),
                ('heading_ta', models.CharField(blank=True, default='', max_length=255)),
                ('body_en', models.TextField(blank=True, default='')),
                ('body_ms', models.TextField(blank=True, default='')),
                ('body_ta', models.TextField(blank=True, default='')),
                ('is_quiz_candidate', models.BooleanField(default=False)),
                ('quiz_en', models.JSONField(blank=True, default=dict)),
                ('quiz_ms', models.JSONField(blank=True, default=dict)),
                ('quiz_ta', models.JSONField(blank=True, default=dict)),
                ('quiz_generated_model', models.CharField(blank=True, default='', max_length=80)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='scholarship.contracttemplate')),
            ],
            options={
                'db_table': 'contract_clauses',
                'ordering': ['template_id', 'order'],
            },
        ),
        migrations.AddField(
            model_name='bursaryagreement',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='scholarship.contracttemplate'),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='comprehension_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scholarship.contracttemplate'),
        ),
        migrations.CreateModel(
            name='PaymentScheduleRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway', models.CharField(max_length=40)),
                ('variant', models.CharField(blank=True, default='', max_length=20)),
                ('label_en', models.CharField(blank=True, default='', max_length=120)),
                ('label_ms', models.CharField(blank=True, default='', max_length=120)),
                ('label_ta', models.CharField(blank=True, default='', max_length=120)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_month', models.PositiveSmallIntegerField()),
                ('paid_offsets', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_rows', to='scholarship.contracttemplate')),
            ],
            options={
                'db_table': 'contract_payment_schedule_rows',
                'ordering': ['template_id', 'sort_order', 'pathway', 'variant'],
            },
        ),
        migrations.AddConstraint(
            model_name='contracttemplate',
            constraint=models.UniqueConstraint(fields=('organisation', 'version'), name='uniq_contract_template_org_version'),
        ),
        migrations.AddConstraint(
            model_name='contractclause',
            constraint=models.UniqueConstraint(fields=('template', 'order'), name='uniq_contract_clause_template_order'),
        ),
        migrations.AddConstraint(
            model_name='paymentschedulerow',
            constraint=models.UniqueConstraint(fields=('template', 'pathway', 'variant'), name='uniq_contract_schedule_template_pathway_variant'),
        ),
    ]
