# Generated by Django 5.2.15 on 2026-07-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_partnerorganisation_show_in_apply'),
        ('scholarship', '0103_contract_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='witness_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.partnerorganisation'),
        ),
    ]
