# Generated by Django 5.2.15 on 2026-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0104_scholarshipapplication_witness_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractclause',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
