# Generated by Django 5.2.15 on 2026-07-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0105_contractclause_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='supported_semesters',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
