# Generated by Django 5.2.15 on 2026-07-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0106_scholarshipapplication_supported_semesters'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttemplate',
            name='counterparty_address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
