# Generated by Django 5.2.15 on 2026-07-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0107_contracttemplate_counterparty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='rejection_comments',
            field=models.TextField(blank=True, default='', help_text="The rejecting admin's reason, recorded verbatim (bucket 'incomplete'); internal, never emailed"),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='pending_rejection_category',
            field=models.CharField(blank=True, choices=[('merit', 'Did not meet the academic/merit floor'), ('need', 'Did not meet the financial-need criteria'), ('ineligible', 'Out of scope / ineligible'), ('interview', 'Reviewed but not selected'), ('contractual', 'Failed post-award contractual steps'), ('incomplete', 'Did not complete the application')], default='', help_text='A scheduled-but-unrevealed decline bucket (cool-off); blank = none pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('merit', 'Did not meet the academic/merit floor'), ('need', 'Did not meet the financial-need criteria'), ('ineligible', 'Out of scope / ineligible'), ('interview', 'Reviewed but not selected'), ('contractual', 'Failed post-award contractual steps'), ('incomplete', 'Did not complete the application')], default='', help_text="Why the application was rejected; blank unless status='rejected'", max_length=20),
        ),
    ]
