# Generated by Django 5.2.15 on 2026-07-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0108_org_admin_reject_incomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrun',
            name='finance_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrun',
            name='finance_signed_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='paymentrun',
            name='finance_signed_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('admin_signed', 'Admin signed'), ('finance_checked', 'Finance checked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
