# Generated by Django 5.2.16 on 2026-07-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0109_paymentrun_finance_signed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='nudge_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
