# Generated by Django 5.2.16 on 2026-07-24 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_alter_partneradmin_role'),
        ('scholarship', '0110_application_nudge_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Bug report'), ('feature', 'Feature request')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('triaged', 'Triaged'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('deferred', 'Deferred'), ('scheduled', 'Scheduled'), ('done', 'Done'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('clarifications', models.JSONField(blank=True, default=list)),
                ('ai_run_count', models.PositiveSmallIntegerField(default=0)),
                ('ai_draft_kind', models.CharField(blank=True, default='', max_length=10)),
                ('ai_draft_lane', models.CharField(blank=True, default='', max_length=20)),
                ('ai_draft_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('ai_draft_note', models.TextField(blank=True, default='')),
                ('ai_draft_model', models.CharField(blank=True, default='', max_length=50)),
                ('ai_draft_at', models.DateTimeField(blank=True, null=True)),
                ('triaged_kind', models.CharField(blank=True, default='', max_length=10)),
                ('lane', models.CharField(blank=True, default='', max_length=20)),
                ('triage_note', models.TextField(blank=True, default='')),
                ('triaged_at', models.DateTimeField(blank=True, null=True)),
                ('quote_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('quote_margin_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quote_note', models.TextField(blank=True, default='')),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('declined_by_role', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_requests', to='courses.partnerorganisation')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_org_requests', to='courses.partneradmin')),
            ],
            options={
                'db_table': 'org_requests',
                'ordering': ('-created_at',),
            },
        ),
    ]
