# Generated by Django 5.2.16 on 2026-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0111_orgrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgrequest',
            name='component',
            field=models.CharField(blank=True, choices=[('applications', 'B40 Applications'), ('students', 'Students'), ('sponsors', 'Sponsors'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('sources', 'Sources'), ('course_data', 'Course Data'), ('administration', 'Administration'), ('access', 'Sign-in & access'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orgrequest',
            name='steps_to_reproduce',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='orgrequest',
            name='urgency',
            field=models.CharField(blank=True, choices=[('blocking', 'Blocking'), ('important', 'Important'), ('nice_to_have', 'Nice to have')], default='', max_length=20),
        ),
    ]
