# Generated by Django 5.2.16 on 2026-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0112_orgrequest_component_orgrequest_steps_to_reproduce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgrequest',
            name='component',
            field=models.CharField(blank=True, choices=[('applications', 'B40 Applications'), ('applications_student_details', 'Student details'), ('applications_documents', 'Documents'), ('applications_ai_prediction', 'AI Prediction & verdicts'), ('applications_queries', 'Queries & blockers'), ('applications_interview', 'Interview'), ('applications_decision', 'Recommendation & QC'), ('applications_agreement', 'Bursary agreement'), ('applications_student_profile', 'Student profile (sponsor-facing)'), ('sponsors', 'Sponsors'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('sources', 'Sources'), ('administration', 'Administration'), ('access', 'Sign-in & access'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
