# Generated by Django 5.2.16 on 2026-07-24 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_alter_partneradmin_role'),
        ('scholarship', '0113_alter_orgrequest_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='scholarship.orgrequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_request_attachments', to='courses.partneradmin')),
            ],
            options={
                'db_table': 'org_request_attachments',
                'ordering': ['id'],
            },
        ),
    ]
