# Generated by Django 5.2.16 on 2026-07-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0114_orgrequestattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='vircle_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
