# Generated by Django 5.2.16 on 2026-07-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_alter_partneradmin_role'),
        ('scholarship', '0115_application_vircle_activated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('gemini', 'Gemini'), ('vision_ocr', 'Cloud Vision OCR'), ('openai', 'OpenAI'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('model', models.CharField(blank=True, default='', help_text='The provider model name (AI only), e.g. gemini-2.5-flash.', max_length=80)),
                ('source', models.CharField(blank=True, default='', help_text='The call-path tag, e.g. doc_extract, ic_fallback, profile_draft, report, or an email/whatsapp function tag.', max_length=40)),
                ('quantity', models.IntegerField(default=1)),
                ('input_tokens', models.IntegerField(blank=True, help_text="Prompt token count (AI only), from the provider response's usage metadata.", null=True)),
                ('output_tokens', models.IntegerField(blank=True, help_text='Completion token count (AI only).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, help_text='The application in hand when known (SET_NULL so purging a case never deletes its billing history).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='scholarship.scholarshipapplication')),
                ('organisation', models.ForeignKey(blank=True, help_text='The tenant this billable call is attributed to. NULL = platform-base work (course-selector reports, ops mail), kept for reconciliation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usage_events', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'usage_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation', 'created_at'], name='usage_org_created_idx')],
            },
        ),
    ]
