# Generated by Django 5.2.16 on 2026-07-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0116_usageevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttemplate',
            name='version',
            field=models.CharField(max_length=50),
        ),
    ]
