"""Platform programme layer — schema (2026-07-26).

Adds ``Programme`` (the durable gift level) plus the two additive, NULLABLE FKs that
hang the existing data off it. Purely additive: the live code never references the new
columns until the reading code deploys, so this is safe to apply ahead of any deploy.
The seed + backfill is the SEPARATE data migration 0119.

MIGRATE-FIRST PROD DDL (hand-written — do NOT use `manage.py sqlmigrate`; the local dev
DB is SQLite and emits a destructive-looking full table rebuild for an AddField, while
prod is Postgres where the same thing is a plain ALTER TABLE ADD COLUMN. See
docs/lessons.md, Payments module Sprint P3). Types mirror the live
`information_schema` (all ids are bigint):

    CREATE TABLE scholarship_programmes (
        id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code            varchar(50)  NOT NULL UNIQUE,
        name_en         varchar(200) NOT NULL,
        name_ms         varchar(200) NOT NULL,
        name_ta         varchar(200) NOT NULL,
        is_active       boolean      NOT NULL,
        created_at      timestamptz  NOT NULL,
        organisation_id bigint       NOT NULL
            REFERENCES partner_organisations(id) DEFERRABLE INITIALLY DEFERRED
    );
    CREATE INDEX scholarship_programmes_organisation_id_idx
        ON scholarship_programmes (organisation_id);
    CREATE INDEX scholarship_programmes_code_like_idx
        ON scholarship_programmes (code varchar_pattern_ops);

    ALTER TABLE scholarship_cohorts      ADD COLUMN programme_id bigint NULL
        REFERENCES scholarship_programmes(id) DEFERRABLE INITIALLY DEFERRED;
    ALTER TABLE scholarship_applications ADD COLUMN programme_id bigint NULL
        REFERENCES scholarship_programmes(id) DEFERRABLE INITIALLY DEFERRED;
    CREATE INDEX scholarship_cohorts_programme_id_idx
        ON scholarship_cohorts (programme_id);
    CREATE INDEX scholarship_applications_programme_id_idx
        ON scholarship_applications (programme_id);

Then insert the two django_migrations rows (0118, 0119) so Django does not re-run them.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_alter_partneradmin_role'),
        ('scholarship', '0117_contracttemplate_version_len_50'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="URL-safe slug, e.g. 'brightpath-flagship', 'brightpath-sabah'", max_length=50, unique=True)),
                ('name_en', models.CharField(max_length=200)),
                ('name_ms', models.CharField(blank=True, default='', max_length=200)),
                ('name_ta', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(help_text='The tenant organisation that runs this gift programme.', on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'scholarship_programmes',
                'ordering': ['organisation_id', 'code'],
            },
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Gift programme this application belongs to (denormalised from cohort.programme; set in save()).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='scholarship.programme'),
        ),
        migrations.AddField(
            model_name='scholarshipcohort',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='The gift programme this annual intake belongs to (platform programme layer). The programme never lapses; intakes cycle.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='scholarship.programme'),
        ),
    ]
