# Generated by Django 5.2.15 on 2026-07-25 18:04

"""Funds per programme — schema (P2, 2026-07-26).

Additive, nullable FK so a donation carries the gift programme it was restricted to.
Nothing reads it until the balance code deploys, so this is safe ahead of any deploy.
The backfill is the separate data migration 0121.

MIGRATE-FIRST PROD DDL (hand-written — never `manage.py sqlmigrate`; local is SQLite,
prod is Postgres. See docs/lessons.md):

    ALTER TABLE sponsor_donations ADD COLUMN programme_id bigint NULL
        REFERENCES scholarship_programmes(id) DEFERRABLE INITIALLY DEFERRED;
    CREATE INDEX sponsor_donations_programme_id_idx
        ON sponsor_donations (programme_id);

Then insert the django_migrations rows for 0120 and 0121.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0119_seed_flagship_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='The gift programme this donation is restricted to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='scholarship.programme'),
        ),
    ]
