# Generated by Django 5.2.15 on 2026-07-25 23:10

"""Sponsor programme membership — schema (P3, 2026-07-26).

A sponsor's acceptance into one gift programme. The ACCOUNT stays platform-level; acceptance
is per programme and survives the year rollover. Purely additive — nothing reads it until the
P3 code deploys. Backfill is the separate data migration 0123.

MIGRATE-FIRST PROD DDL (hand-written — never `manage.py sqlmigrate`; local is SQLite, prod is
Postgres. Mirror the sibling RLS convention: every app table runs RLS ENABLED with exactly one
`Backend service role only` policy — see docs/lessons.md):

    CREATE TABLE sponsor_programme_memberships (
        id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        status       varchar(20)  NOT NULL,
        vetted_by    varchar(200) NOT NULL,
        vetted_at    timestamptz  NULL,
        created_at   timestamptz  NOT NULL,
        updated_at   timestamptz  NOT NULL,
        sponsor_id   bigint NOT NULL REFERENCES sponsors(id) DEFERRABLE INITIALLY DEFERRED,
        programme_id bigint NOT NULL REFERENCES scholarship_programmes(id) DEFERRABLE INITIALLY DEFERRED,
        CONSTRAINT uniq_sponsor_programme_membership UNIQUE (sponsor_id, programme_id)
    );
    CREATE INDEX sponsor_programme_memberships_sponsor_id_idx
        ON sponsor_programme_memberships (sponsor_id);
    CREATE INDEX sponsor_programme_memberships_programme_id_idx
        ON sponsor_programme_memberships (programme_id);
    ALTER TABLE sponsor_programme_memberships ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Backend service role only" ON sponsor_programme_memberships
        FOR ALL TO service_role USING (true) WITH CHECK (true);

Then insert the django_migrations rows for 0122 and 0123.

**Confirm the sponsors table name against information_schema before running** — the model's
db_table is what the FK must target.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0121_backfill_donation_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorProgrammeMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('vetted_by', models.CharField(blank=True, default='', max_length=200)),
                ('vetted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_memberships', to='scholarship.programme')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programme_memberships', to='scholarship.sponsor')),
            ],
            options={
                'db_table': 'sponsor_programme_memberships',
                'ordering': ['sponsor_id', 'programme_id'],
                'constraints': [models.UniqueConstraint(fields=('sponsor', 'programme'), name='uniq_sponsor_programme_membership')],
            },
        ),
    ]
