# Generated by Django 5.2.15 on 2026-07-25 23:25

"""Wallet credit — provenance + sign-off chain (P4, 2026-07-26).

Nine additive columns on ``sponsor_donations``. Defaults are chosen so EXISTING rows are
untouched in meaning: ``source='legacy'`` (provenance was never recorded, do not claim
otherwise) and ``status='confirmed'`` (money that already arrived is confirmed by arrival),
so every current balance reads exactly as it did. No data migration is needed.

MIGRATE-FIRST PROD DDL (hand-written — never `manage.py sqlmigrate`; local is SQLite, prod
is Postgres. See docs/lessons.md):

    ALTER TABLE sponsor_donations
      ADD COLUMN source              varchar(20)  NOT NULL DEFAULT 'legacy',
      ADD COLUMN external_reference  varchar(120) NOT NULL DEFAULT '',
      ADD COLUMN status              varchar(20)  NOT NULL DEFAULT 'confirmed',
      ADD COLUMN recorded_by         varchar(200) NOT NULL DEFAULT '',
      ADD COLUMN recorded_at         timestamptz  NULL,
      ADD COLUMN finance_checked_by  varchar(200) NOT NULL DEFAULT '',
      ADD COLUMN finance_checked_at  timestamptz  NULL,
      ADD COLUMN confirmed_by        varchar(200) NOT NULL DEFAULT '',
      ADD COLUMN confirmed_at        timestamptz  NULL;
    -- Django keeps defaults app-side (the 0061 precedent):
    ALTER TABLE sponsor_donations
      ALTER COLUMN source DROP DEFAULT, ALTER COLUMN external_reference DROP DEFAULT,
      ALTER COLUMN status DROP DEFAULT, ALTER COLUMN recorded_by DROP DEFAULT,
      ALTER COLUMN finance_checked_by DROP DEFAULT, ALTER COLUMN confirmed_by DROP DEFAULT;

Post-check: every existing row reads source='legacy', status='confirmed', and the sum of
CONFIRMED donations per programme is unchanged (balances must not move).
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0123_backfill_sponsor_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='confirmed_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='donation',
            name='finance_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='finance_checked_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='recorded_by',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='donation',
            name='source',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('admin_recorded', 'Admin-recorded'), ('gateway', 'Gateway'), ('mock', 'Mock')], default='legacy', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('admin_signed', 'Admin signed'), ('finance_checked', 'Finance checked'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20),
        ),
    ]
