"""Partner-organisation comms — schema (2026-07-26).

Two new tables plus two nullable stamps on `scholarship_applications`. Purely additive:
nothing reads any of it until the S1 code deploys, and nothing SENDS until both
`PARTNER_COMMS_ENABLED` and a template's own `enabled` flag are on.

Design notes worth carrying (full rationale in docs/plans/2026-07-26-partner-comms-roadmap.md):

* `partner_email_templates` — five rows, one per email kind, seeded by
  `manage.py seed_partner_email_templates`. `enabled` lives HERE, not on an
  (organisation, kind) pair: owner ruling 2026-07-26 is that an email is on for every
  qualifying partner or off for all of them, so there is no per-organisation setting.
* `partner_email_log` — one row per attempt, INCLUDING failures and no-recipient skips.
  Its newest row for an (organisation, kind) pair is also where the weekly digest reads
  the previous `fingerprint` from, so send-state has exactly one home.
* the two stamps mirror `SponsorProfile.realtime_notified_at`: idempotency for a batched
  hourly sweep, cheaper and simpler than a per-(application, kind) table.

MIGRATE-FIRST PROD DDL (hand-written — never `manage.py sqlmigrate`; local is SQLite, prod is
Postgres. Mirror the sibling RLS convention: every app table runs RLS ENABLED with exactly one
`Backend service role only` policy — see docs/lessons.md):

    CREATE TABLE partner_email_templates (
        id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kind              varchar(32)  NOT NULL UNIQUE,
        enabled           boolean      NOT NULL,
        subject           varchar(255) NOT NULL,
        body              text         NOT NULL,
        updated_by_email  varchar(254) NOT NULL,
        created_at        timestamptz  NOT NULL,
        updated_at        timestamptz  NOT NULL
    );
    ALTER TABLE partner_email_templates ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Backend service role only" ON partner_email_templates
        FOR ALL TO service_role USING (true) WITH CHECK (true);

    CREATE TABLE partner_email_log (
        id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        kind             varchar(32)  NOT NULL,
        recipients       jsonb        NOT NULL,
        subject          varchar(255) NOT NULL,
        fingerprint      varchar(64)  NOT NULL,
        students         integer      NOT NULL,
        ok               boolean      NOT NULL,
        note             varchar(200) NOT NULL,
        sent_at          timestamptz  NOT NULL,
        organisation_id  bigint NOT NULL REFERENCES partner_organisations(id)
                             DEFERRABLE INITIALLY DEFERRED,
        application_id   bigint NULL REFERENCES scholarship_applications(id)
                             DEFERRABLE INITIALLY DEFERRED
    );
    CREATE INDEX partner_email_log_organisation_id_idx ON partner_email_log (organisation_id);
    CREATE INDEX partner_email_log_application_id_idx  ON partner_email_log (application_id);
    CREATE INDEX partner_email_org_kind_idx ON partner_email_log (organisation_id, kind, sent_at DESC);
    ALTER TABLE partner_email_log ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Backend service role only" ON partner_email_log
        FOR ALL TO service_role USING (true) WITH CHECK (true);

    ALTER TABLE scholarship_applications
        ADD COLUMN partner_awaiting_notified_at timestamptz NULL,
        ADD COLUMN partner_awarded_notified_at  timestamptz NULL;

Then insert the django_migrations row for 0128.

**Confirm `partner_organisations` and `scholarship_applications` against information_schema
before running** — the FK must target the models' real `db_table` names.

Post-check:
    SELECT relname, relrowsecurity FROM pg_class
     WHERE relname IN ('partner_email_templates', 'partner_email_log');   -- both true
    SELECT tablename, policyname FROM pg_policies
     WHERE tablename IN ('partner_email_templates', 'partner_email_log'); -- one policy each
Both new columns exist and are NULL on every row (no backfill — a stamp means "we have told
the partner", and we have told nobody yet; back-dating them would silence the first sweep).
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_alter_partneradmin_role'),
        ('scholarship', '0127_backfill_paymentrun_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='partner_awaiting_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplication',
            name='partner_awarded_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PartnerEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly_summary', 'Weekly summary'), ('shortlisted_followup', 'Chase list'), ('awaiting_review', 'Awaiting review'), ('awarded', 'Awarded'), ('assigned', 'A student joins their list')], max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'partner_email_templates',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='PartnerEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly_summary', 'Weekly summary'), ('shortlisted_followup', 'Chase list'), ('awaiting_review', 'Awaiting review'), ('awarded', 'Awarded'), ('assigned', 'A student joins their list')], max_length=32)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('students', models.IntegerField(default=0, help_text='How many students the email covered.')),
                ('ok', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', help_text="Why nothing was sent, e.g. 'no_recipient', 'unchanged'.", max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_emails', to='scholarship.scholarshipapplication')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_email_log', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'partner_email_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['organisation', 'kind', '-sent_at'], name='partner_email_org_kind_idx')],
            },
        ),
    ]
