"""Platform cost ledger — schema (2026-07-26).

ONE new table, purely additive. Nothing reads it and nothing writes it except two management
commands, so it is inert until somebody runs a sync. No behaviour changes on deploy.

Why a second ledger rather than prices on `usage_events` (full rationale in
docs/plans/2026-07-24-billing-sources-investigation.md):
the meter accounts for ~RM20 of an RM88 June bill. The remainder is infrastructure driven by
our own cron schedule and deploy pace, not by tenant activity. Pricing it per-org would invent
precision that does not exist. This table records the INVOICE at its own grain (month × SKU)
and marks each line attributable or not.

`provenance` is load-bearing, not decoration: GCP can be pulled from the BigQuery billing
export and re-derived at will; Supabase has no supported billing API, so its figures are typed
from a PDF by a human. A reconciliation that cannot tell those apart is not an audit.

The unique constraint on (period_month, source, service, sku) is what makes the sync an
idempotent UPSERT — re-running a month CORRECTS it rather than doubling it.

MIGRATE-FIRST PROD DDL (hand-written — never `manage.py sqlmigrate`; local is SQLite, prod is
Postgres. Mirror the sibling RLS convention: every app table runs RLS ENABLED with exactly one
`Backend service role only` policy — see docs/lessons.md):

    CREATE TABLE platform_costs (
        id            bigint         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        period_month  varchar(7)     NOT NULL,
        source        varchar(20)    NOT NULL,
        service       varchar(120)   NOT NULL,
        sku           varchar(200)   NOT NULL,
        amount_myr    numeric(12,2)  NOT NULL,
        attributable  boolean        NOT NULL,
        provenance    varchar(10)    NOT NULL,
        note          text           NOT NULL,
        recorded_at   timestamptz    NOT NULL,
        updated_at    timestamptz    NOT NULL,
        CONSTRAINT platform_cost_unique_line
            UNIQUE (period_month, source, service, sku)
    );
    CREATE INDEX platform_cost_month_idx ON platform_costs (period_month, source);

    ALTER TABLE platform_costs ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Backend service role only" ON platform_costs
        FOR ALL TO service_role USING (true) WITH CHECK (true);

    INSERT INTO django_migrations (app, name, applied)
        VALUES ('scholarship', '0129_platform_cost', NOW());

POST-CHECK: `SELECT count(*) FROM platform_costs;` returns 0 (nothing backfills on create), and
the Supabase Security Advisor reports no new finding for `platform_costs`.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0128_partner_comms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.CharField(help_text="Billing month as 'YYYY-MM'. The grain of an invoice, not of an event.", max_length=7)),
                ('source', models.CharField(choices=[('gcp', 'Google Cloud Platform'), ('supabase', 'Supabase'), ('brevo', 'Brevo'), ('twilio', 'Twilio'), ('other', 'Other')], max_length=20)),
                ('service', models.CharField(blank=True, default='', help_text="Provider service, e.g. 'Cloud Run', 'Artifact Registry'.", max_length=120)),
                ('sku', models.CharField(blank=True, default='', help_text='Provider SKU — the grain that actually explains a bill. Reading June by SKU is what revealed Cloud Run JOBS (RM33) outranked Artifact Registry.', max_length=200)),
                ('amount_myr', models.DecimalField(decimal_places=2, help_text='Cost in MYR, as invoiced. Decimal, never float — this is money.', max_digits=12)),
                ('attributable', models.BooleanField(default=False, help_text='True when this line moves with TENANT activity (per-document OCR, AI, egress). False for platform-driven cost (cron compute, CI storage) — that belongs in a platform fee, not a metered charge.')),
                ('provenance', models.CharField(choices=[('measured', "Measured — pulled from the provider's own billing data"), ('entered', 'Entered by hand from an invoice')], max_length=10)),
                ('note', models.TextField(blank=True, default='', help_text='Anything a future reader needs in order to trust the figure — invoice number, what was excluded, an attribution caveat.')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_costs',
                'ordering': ['-period_month', 'source', '-amount_myr'],
                'indexes': [models.Index(fields=['period_month', 'source'], name='platform_cost_month_idx')],
                'constraints': [models.UniqueConstraint(fields=('period_month', 'source', 'service', 'sku'), name='platform_cost_unique_line')],
            },
        ),
    ]
