# Generated by Django 5.2.15 on 2026-07-26 12:56

"""Platform cost ledger — hold a foreign-currency invoice honestly (2026-07-26).

Same-day follow-up to 0129, prompted by the first real Supabase invoices: they are denominated
in **USD** ($25.00/month, invoice refs TPTHYS-0000N), and 0129 modelled only `amount_myr`. That
assumed every provider bills in ringgit — GCP does, Supabase does not.

Converting USD→MYR needs a rate, and a rate typed from memory is precisely the
"estimate dressed as a fact" this ledger exists to prevent. So:

* `currency` + `amount_original` — record the invoice in ITS OWN denomination, unaltered.
* `fx_rate` — the conversion becomes a separate, visible, auditable step.
* `amount_myr` becomes **NULLABLE**. "We hold the invoice but do not yet know what it cost in
  ringgit" is a real state and deserves to be representable. `month_totals` counts such rows
  and reports `is_complete: False`, so a total is never silently understated — the alternative
  (a placeholder figure) gets quoted as though it were true.
* `invoice_ref` — its own column, not buried in free text. It is how a figure is traced back to
  the document it came from, which is the point of an auditable ledger.
* `period_note` — Supabase invoices on the **8th**, so its period straddles two calendar months
  while GCP's lines are calendar-month. Comparing them without recording that is comparing
  unlike windows.

Purely additive apart from dropping a NOT NULL, which no existing row relies on (the 17 GCP
lines loaded under 0129 all carry a value).

MIGRATE-FIRST PROD DDL (hand-written — never `manage.py sqlmigrate`; local is SQLite, prod is
Postgres):

    ALTER TABLE platform_costs ADD COLUMN currency        varchar(3)    NOT NULL DEFAULT 'MYR';
    ALTER TABLE platform_costs ADD COLUMN amount_original numeric(12,2) NULL;
    ALTER TABLE platform_costs ADD COLUMN fx_rate         numeric(10,4) NULL;
    ALTER TABLE platform_costs ADD COLUMN invoice_ref     varchar(60)   NOT NULL DEFAULT '';
    ALTER TABLE platform_costs ADD COLUMN period_note     varchar(120)  NOT NULL DEFAULT '';
    ALTER TABLE platform_costs ALTER COLUMN amount_myr DROP NOT NULL;

    INSERT INTO django_migrations (app, name, applied)
        VALUES ('scholarship', '0130_platform_cost_currency', NOW());

POST-CHECK: the 17 June GCP rows still sum to RM88.44 and none has a NULL `amount_myr`; every
one reads `currency = 'MYR'`.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0129_platform_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformcost',
            name='amount_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The figure printed on the invoice, in `currency`. Null for MYR invoices where amount_myr IS the invoiced figure.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='platformcost',
            name='currency',
            field=models.CharField(default='MYR', help_text='ISO code the invoice is denominated in. GCP = MYR, Supabase = USD.', max_length=3),
        ),
        migrations.AddField(
            model_name='platformcost',
            name='fx_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Rate used to derive amount_myr from amount_original. Prefer the rate your card was actually charged at — that is the real cost — over a spot rate.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='platformcost',
            name='invoice_ref',
            field=models.CharField(blank=True, default='', help_text="The provider's own invoice number (e.g. 'TPTHYS-00007'). Its own column, not buried in a note: it is how a figure is traced back to the document it came from, which is the whole point of an auditable ledger.", max_length=60),
        ),
        migrations.AddField(
            model_name='platformcost',
            name='period_note',
            field=models.CharField(blank=True, default='', help_text="Set when the provider's billing period does not match the calendar month — e.g. Supabase invoices on the 8th, so a period straddles two months. Without this, a cross-provider reconciliation compares unlike periods.", max_length=120),
        ),
        migrations.AlterField(
            model_name='platformcost',
            name='amount_myr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost in MYR — the common denominator every total is summed in. Decimal, never float: this is money. **Nullable on purpose.** "We hold the invoice but do not yet know what it cost us in ringgit" is a real and honest state; a placeholder number in a money column gets quoted as if it were true. Rows left null are counted and reported as incomplete, never silently dropped from a total.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='platformcost',
            name='note',
            field=models.TextField(blank=True, default='', help_text='Anything a future reader needs in order to trust the figure — what was excluded, an attribution caveat, why a rate was chosen.'),
        ),
    ]
