# Generated by Django 5.2.15 on 2026-07-27 02:51

import django.db.models.deletion
"""Billing rates (platform-side) + build hours (org-side) — schema (2026-07-27).

Owner design: hours are recorded on the ORG side; the conversion rate and the per-category
margins live PLATFORM-side as editable values. Two new tables, purely additive, inert until
somebody sets a rate — nothing reads either one on deploy.

`billing_rates` is EFFECTIVE-DATED. A rate is a term, not a setting, and a term has a date. A
single mutable number would mean editing the hourly rate in September silently re-prices
August's invoice — a quiet retroactive change to a bill, which is exactly the thing that
destroys trust in one. So a new value is a NEW ROW with a later `effective_from`; the old row
stays as the audit trail, and `rate_in_force()` always asks "what was true on THAT day?".

**No defaults are seeded for development.** The infrastructure margin (15%) is a decision the
owner has taken and is seeded; the hourly rate and development margin have never been set, and
`platform_cost.rate_in_force` RAISES rather than defaulting. An unbilled month is a visible
problem somebody fixes; a month billed at an invented rate is an invoice you have to withdraw.

`org_build_hours.basis` is REQUIRED by design. No time tracker has ever existed here, so every
hours figure is a reconstruction — from working days, a sprint span, memory. That is legitimate
input only if the reconstruction travels with the number: "70 working days at 4h" is auditable,
"280" is not.

MIGRATE-FIRST PROD DDL (hand-written — never `manage.py sqlmigrate`; local is SQLite, prod is
Postgres. Sibling RLS convention: RLS ENABLED + exactly one `Backend service role only` policy):

    CREATE TABLE billing_rates (
        id                bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category          varchar(20)   NOT NULL,
        kind              varchar(20)   NOT NULL,
        value             numeric(10,2) NOT NULL,
        effective_from    date          NOT NULL,
        updated_by_email  varchar(254)  NOT NULL,
        note              text          NOT NULL,
        created_at        timestamptz   NOT NULL,
        CONSTRAINT billing_rate_unique_effective UNIQUE (category, kind, effective_from)
    );
    ALTER TABLE billing_rates ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Backend service role only" ON billing_rates
        FOR ALL TO service_role USING (true) WITH CHECK (true);

    CREATE TABLE org_build_hours (
        id                 bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        organisation_id    bigint       NOT NULL REFERENCES partner_organisations(id),
        period_month       varchar(7)   NOT NULL,
        module             varchar(200) NOT NULL,
        hours              numeric(8,1) NOT NULL,
        basis              text         NOT NULL,
        recorded_by_email  varchar(254) NOT NULL,
        recorded_at        timestamptz  NOT NULL,
        updated_at         timestamptz  NOT NULL
    );
    CREATE INDEX build_hours_org_idx ON org_build_hours (organisation_id, period_month);
    ALTER TABLE org_build_hours ENABLE ROW LEVEL SECURITY;
    CREATE POLICY "Backend service role only" ON org_build_hours
        FOR ALL TO service_role USING (true) WITH CHECK (true);

    -- The one decision already taken (docs/decisions.md 2026-07-26): infrastructure +15%.
    INSERT INTO billing_rates (category, kind, value, effective_from, updated_by_email, note, created_at)
        VALUES ('infrastructure', 'margin_pct', 15.00, '2026-07-01', '',
                'Owner decision 2026-07-26: spot FX + 15%. Superseded the undecided 15-30% range.',
                NOW());

    INSERT INTO django_migrations (app, name, applied)
        VALUES ('scholarship', '0131_billing_rates_and_hours', NOW());

POST-CHECK: `billing_rates` holds exactly 1 row (infrastructure margin 15); `org_build_hours`
is empty; both report RLS enabled with one policy.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0066_alter_partneradmin_role'),
        ('scholarship', '0130_platform_cost_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure (platform fee)'), ('metered', 'Metered usage'), ('development', 'Development hours')], max_length=20)),
                ('kind', models.CharField(choices=[('margin_pct', 'Margin (%) added to the category'), ('hourly_rate', 'Hourly rate (RM per hour)')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent for margin_pct (15 = +15%), RM/hour for hourly_rate. Decimal, never float — this ends up on an invoice.', max_digits=10)),
                ('effective_from', models.DateField(help_text='The day this value takes effect. A month is billed on the value in force during that month, so changing a rate never re-prices a closed month.')),
                ('updated_by_email', models.EmailField(blank=True, default='', help_text='Who set it. A rate change is a commercial act and should have a name on it.', max_length=254)),
                ('note', models.TextField(blank=True, default='', help_text='Why this value. A future reader asking "why 15%?" deserves an answer here rather than in somebody\'s memory.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_rates',
                'ordering': ['category', 'kind', '-effective_from'],
                'constraints': [models.UniqueConstraint(fields=('category', 'kind', 'effective_from'), name='billing_rate_unique_effective')],
            },
        ),
        migrations.CreateModel(
            name='OrgBuildHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.CharField(help_text="'YYYY-MM' the work is billed in.", max_length=7)),
                ('module', models.CharField(help_text="What was built, in the owner's words — e.g. 'Payments module', 'Programme layer P1a-P4b'. This is what the tenant reads on the invoice.", max_length=200)),
                ('hours', models.DecimalField(decimal_places=1, help_text='Hours spent. One decimal place: nobody can honestly reconstruct minutes.', max_digits=8)),
                ('basis', models.TextField(help_text='REQUIRED. How this figure was arrived at — the working-day count, the sprint span, whatever it was. There is no time tracker, so the number is a reconstruction and is only trustworthy if it says so.')),
                ('recorded_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(help_text='The tenant whose modules were built. PROTECT: billing history must outlive any tidy-up of the organisation record.', on_delete=django.db.models.deletion.PROTECT, related_name='build_hours', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'org_build_hours',
                'ordering': ['-period_month', 'organisation'],
                'indexes': [models.Index(fields=['organisation', 'period_month'], name='build_hours_org_idx')],
            },
        ),
    ]
