# Generated by Django 5.2.15 on 2026-07-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0131_billing_rates_and_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
