# Generated by Django 5.2.15 on 2026-07-28 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0132_sponsor_last_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('welcome', 'Welcome — registered, awaiting vetting'), ('approved', 'Approved'), ('rejected', 'Not approved'), ('suspended', 'Suspended'), ('reinstated', 'Reinstated'), ('credit_confirmed', 'Credit confirmed'), ('new_students', 'New students to consider'), ('weekly_digest', 'Weekly digest'), ('referral_invite', 'Invitation to a prospective sponsor')], max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sponsor_email_templates',
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='SponsorEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('welcome', 'Welcome — registered, awaiting vetting'), ('approved', 'Approved'), ('rejected', 'Not approved'), ('suspended', 'Suspended'), ('reinstated', 'Reinstated'), ('credit_confirmed', 'Credit confirmed'), ('new_students', 'New students to consider'), ('weekly_digest', 'Weekly digest'), ('referral_invite', 'Invitation to a prospective sponsor')], max_length=32)),
                ('recipients', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('ok', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', help_text="Why nothing was sent, e.g. 'no_recipient', 'disabled'.", max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_log', to='scholarship.sponsor')),
            ],
            options={
                'db_table': 'sponsor_email_log',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sponsor', 'kind', '-sent_at'], name='sponsor_email_kind_idx')],
            },
        ),
    ]
