# Generated by Django 5.2.15 on 2026-07-28 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0133_sponsor_email_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorTermsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('title_en', models.CharField(blank=True, default='', max_length=255)),
                ('title_ms', models.CharField(blank=True, default='', max_length=255)),
                ('title_ta', models.CharField(blank=True, default='', max_length=255)),
                ('intro_en', models.TextField(blank=True, default='')),
                ('intro_ms', models.TextField(blank=True, default='')),
                ('intro_ta', models.TextField(blank=True, default='')),
                ('created_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('published_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sponsor_terms_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsorTermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('heading_en', models.TextField(blank=True, default='')),
                ('heading_ms', models.TextField(blank=True, default='')),
                ('heading_ta', models.TextField(blank=True, default='')),
                ('body_en', models.TextField(blank=True, default='')),
                ('body_ms', models.TextField(blank=True, default='')),
                ('body_ta', models.TextField(blank=True, default='')),
                ('is_quiz_candidate', models.BooleanField(default=False)),
                ('quiz_en', models.JSONField(blank=True, default=dict)),
                ('quiz_ms', models.JSONField(blank=True, default=dict)),
                ('quiz_ta', models.JSONField(blank=True, default=dict)),
                ('quiz_generated_model', models.CharField(blank=True, default='', max_length=80)),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='scholarship.sponsortermsversion')),
            ],
            options={
                'db_table': 'sponsor_terms_sections',
                'ordering': ['terms_id', 'order'],
                'constraints': [models.UniqueConstraint(fields=('terms', 'order'), name='uniq_sponsor_terms_section_order')],
            },
        ),
        migrations.CreateModel(
            name='SponsorTermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basis', models.CharField(choices=[('accepted', 'Accepted by the sponsor'), ('grandfathered', 'Grandfathered — never asked')], default='accepted', max_length=20)),
                ('signed_name', models.CharField(blank=True, default='', max_length=200)),
                ('registered_name_at_acceptance', models.CharField(blank=True, default='', max_length=200)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('quiz_passed_at', models.DateTimeField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, default='en', max_length=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('granted_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_acceptances', to='scholarship.sponsor')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='scholarship.sponsortermsversion')),
            ],
            options={
                'db_table': 'sponsor_terms_acceptances',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('sponsor', 'terms'), name='uniq_sponsor_terms_acceptance')],
            },
        ),
    ]
