# Generated by Django 5.2.15 on 2026-07-28 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0134_sponsor_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('document', 'Document'), ('question', 'Question')], max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('label_key', models.CharField(max_length=200)),
                ('is_core', models.BooleanField(default=False)),
                ('default_state', models.CharField(choices=[('off', 'Not asked for'), ('optional', 'Offered, never blocks'), ('required', 'Must be provided')], default='off', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'application_items',
                'ordering': ['kind', 'code'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'code'), name='uniq_application_item')],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('off', 'Not asked for'), ('optional', 'Offered, never blocks'), ('required', 'Must be provided')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programme_selections', to='scholarship.applicationitem')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_items', to='scholarship.programme')),
            ],
            options={
                'db_table': 'programme_application_items',
                'ordering': ['programme_id', 'item_id'],
                'constraints': [models.UniqueConstraint(fields=('programme', 'item'), name='uniq_programme_application_item')],
            },
        ),
    ]
