# Generated by Django 5.2.15 on 2026-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0144_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneremaillog',
            name='kind',
            field=models.CharField(choices=[('weekly_summary', 'Weekly summary'), ('shortlisted_followup', 'Chase list'), ('awaiting_review', 'Awaiting review'), ('awarded', 'Awarded'), ('assigned', 'A student joins their list'), ('student_assigned', 'The student is told'), ('reviewer_assigned', 'A case is assigned to a reviewer'), ('qc_returned', 'QC returns a case for revision'), ('qc_rejected', 'QC rejects a case'), ('verdict_due_soon', 'A verdict is due soon'), ('verdict_overdue', 'A verdict is overdue'), ('invite_staff', 'Joining the team'), ('invite_sponsor', 'Inviting a sponsor')], max_length=32),
        ),
        migrations.AlterField(
            model_name='partneremailtemplate',
            name='kind',
            field=models.CharField(choices=[('weekly_summary', 'Weekly summary'), ('shortlisted_followup', 'Chase list'), ('awaiting_review', 'Awaiting review'), ('awarded', 'Awarded'), ('assigned', 'A student joins their list'), ('student_assigned', 'The student is told'), ('reviewer_assigned', 'A case is assigned to a reviewer'), ('qc_returned', 'QC returns a case for revision'), ('qc_rejected', 'QC rejects a case'), ('verdict_due_soon', 'A verdict is due soon'), ('verdict_overdue', 'A verdict is overdue'), ('invite_staff', 'Joining the team'), ('invite_sponsor', 'Inviting a sponsor')], max_length=32, unique=True),
        ),
    ]
