# Generated by Django 5.2.15 on 2026-08-04 00:42
"""One invitation email per group on the Invitations page (owner, 2026-08-04).

`invite_staff` addressed admins and reviewers with one letter that swapped a role label. The owner
asked for them apart, plus a source one — so the four kinds now mirror the four tables exactly.

⚠ **THE ONLY REAL DATABASE WORK HERE IS THE RENAME.** Both `AlterField`s are choices-only and
`sqlmigrate` prints nothing for them (Django choices are validated in Python, never as a Postgres
constraint). The production step is the UPDATE below plus the `django_migrations` ledger row.

The rename is safe to run before the new code is serving: the row keeps its wording, and until the
deploy lands nothing looks for `invite_reviewer`, so the sender simply falls back to the built-in
body — which is byte-identical to what that row holds. There is no window in which anybody is not
written to.
"""

from django.db import migrations, models


def _staff_becomes_reviewer(apps, schema_editor):
    """`invite_staff` → `invite_reviewer`, on both the templates and the send log.

    Guarded rather than blind: if a row somehow already occupies the new name, the old one is left
    alone for a human instead of blowing up on the unique index mid-deploy.
    """
    for model_name in ('PartnerEmailTemplate', 'PartnerEmailLog'):
        model = apps.get_model('scholarship', model_name)
        if model.objects.filter(kind='invite_reviewer').exists():
            continue
        model.objects.filter(kind='invite_staff').update(kind='invite_reviewer')


def _reviewer_becomes_staff(apps, schema_editor):
    for model_name in ('PartnerEmailTemplate', 'PartnerEmailLog'):
        model = apps.get_model('scholarship', model_name)
        if model.objects.filter(kind='invite_staff').exists():
            continue
        model.objects.filter(kind='invite_reviewer').update(kind='invite_staff')


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0145_invite_email_kinds'),
    ]

    operations = [
        migrations.RunPython(_staff_becomes_reviewer, _reviewer_becomes_staff),
        migrations.AlterField(
            model_name='partneremaillog',
            name='kind',
            field=models.CharField(choices=[('weekly_summary', 'Weekly summary'), ('shortlisted_followup', 'Chase list'), ('awaiting_review', 'Awaiting review'), ('awarded', 'Awarded'), ('assigned', 'A student joins their list'), ('student_assigned', 'The student is told'), ('reviewer_assigned', 'A case is assigned to a reviewer'), ('qc_returned', 'QC returns a case for revision'), ('qc_rejected', 'QC rejects a case'), ('verdict_due_soon', 'A verdict is due soon'), ('verdict_overdue', 'A verdict is overdue'), ('invite_admin', 'Joining the team — admin'), ('invite_reviewer', 'Joining the team — reviewer'), ('invite_source', 'Inviting a source organisation'), ('invite_sponsor', 'Inviting a sponsor')], max_length=32),
        ),
        migrations.AlterField(
            model_name='partneremailtemplate',
            name='kind',
            field=models.CharField(choices=[('weekly_summary', 'Weekly summary'), ('shortlisted_followup', 'Chase list'), ('awaiting_review', 'Awaiting review'), ('awarded', 'Awarded'), ('assigned', 'A student joins their list'), ('student_assigned', 'The student is told'), ('reviewer_assigned', 'A case is assigned to a reviewer'), ('qc_returned', 'QC returns a case for revision'), ('qc_rejected', 'QC rejects a case'), ('verdict_due_soon', 'A verdict is due soon'), ('verdict_overdue', 'A verdict is overdue'), ('invite_admin', 'Joining the team — admin'), ('invite_reviewer', 'Joining the team — reviewer'), ('invite_source', 'Inviting a source organisation'), ('invite_sponsor', 'Inviting a sponsor')], max_length=32, unique=True),
        ),
    ]
