# Generated by Django 5.2.15 on 2026-09-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0147_requirements_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipcohort',
            name='min_merit_score',
            field=models.FloatField(blank=True, default=None, help_text="Minimum UPU merit point out of 100 (grades + co-curriculum). SPM applicants only — an STPM applicant's comparable figure is their PNGK, which is min_stpm_pngk. NULL = not applied, which is every cohort today.", null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='income_ceiling',
            field=models.IntegerField(blank=True, help_text='B40 monthly household GROSS income ceiling in RM (DOSM B40 line, RM5,860 in 2024). PRIMARY income gate: a non-STR applicant at or below this passes regardless of household size. NULL together with per_capita_ceiling = the financial test is not applied.', null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='min_spm_a_count',
            field=models.IntegerField(blank=True, default=4, help_text='Minimum SPM grades at A- or better (A+/A/A- all count). NULL = not applied.', null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='min_spm_bplus_count',
            field=models.IntegerField(blank=True, default=5, help_text="Minimum SPM grades at B+ or better — the TOTAL strong count, not the extra beyond the A's (4 A- plus 1 more B+ is stored as 5). NULL = not applied.", null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='min_stpm_pngk',
            field=models.FloatField(blank=True, default=2.9, help_text='Minimum STPM PNGK. NULL = not applied.', null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipcohort',
            name='per_capita_ceiling',
            field=models.IntegerField(blank=True, default=1584, help_text='Per-capita monthly income ceiling in RM (household_income / household_size). SAFETY NET only — applies to non-STR applicants whose gross income is ABOVE income_ceiling, rescuing large households. RM5,860 B40 ceiling / 3.7 avg household = RM1,584 (DOSM 2024). NULL = this rescue is not offered.', null=True),
        ),
    ]
