# Generated by Django 5.2.15 on 2026-09-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0148_sabah_s2a_optional_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Sponsor invitations only: the gift the organisation is inviting them into. NULL = not stated, and registration resolves it if it can.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scholarship.programme'),
        ),
    ]
