# Generated by Django 5.2.15 on 2026-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0149_s_assign_programme_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipcohort',
            name='closes_on',
            field=models.DateField(blank=True, help_text='The date this round is STATED to close. Descriptive only — it closes nothing. NULL means no window was stated.', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipcohort',
            name='opens_on',
            field=models.DateField(blank=True, help_text='The date this round is STATED to open. Descriptive only — it opens nothing; `is_open` is the switch. NULL means no window was stated.', null=True),
        ),
    ]
