# Generated by Django 5.2.15 on 2026-09-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    """The intake year's STATED window — `opens_on` / `closes_on`.

    ⚠ THESE DATES DESCRIBE. THEY OPEN NOTHING. `is_open` is the switch and stays the switch
    (owner ruling, 2026-09-06). Nothing reads these columns to decide whether a student may apply,
    and nothing may be written that does — a clock would fire whether or not the gift's rules and
    questions had been finished.

    ⚠ NULL IS A REAL ANSWER AND THERE IS NO BACKFILL. A round with no stated window is a normal
    round. Inventing dates for the 2026 intake, which has already run, would be fiction on an
    audited row.

    ── APPLIED MIGRATE-FIRST TO PRODUCTION 2026-09-07, ledger row recorded in the same statement.
    Hand-written because `sqlmigrate` renders SQLite on this box and prints a table rebuild:

        ALTER TABLE scholarship_cohorts ADD COLUMN opens_on date NULL;
        ALTER TABLE scholarship_cohorts ADD COLUMN closes_on date NULL;
        INSERT INTO django_migrations (app, name, applied)
        VALUES ('scholarship', '0150_gift_setup_flow_intake_window', NOW());

    Verified after: both columns present, ledger row 1, 1 round, **0 rounds carrying a window**,
    scholarship ledger contiguous 1–150 with no gaps. No existing table, so no RLS work.
    """

    dependencies = [
        ('scholarship', '0149_s_assign_programme_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipcohort',
            name='closes_on',
            field=models.DateField(blank=True, help_text='The date this round is STATED to close. Descriptive only — it closes nothing. NULL means no window was stated.', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipcohort',
            name='opens_on',
            field=models.DateField(blank=True, help_text='The date this round is STATED to open. Descriptive only — it opens nothing; `is_open` is the switch. NULL means no window was stated.', null=True),
        ),
    ]
