# Generated by Django 5.2.15 on 2026-09-08 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0150_gift_setup_flow_intake_window'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipcohort',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='When this round was closed FOR GOOD. Terminal — nothing in the product clears it. NULL means the round can still be reopened.', null=True),
        ),
        migrations.AddField(
            model_name='scholarshipcohort',
            name='finished_by',
            field=models.CharField(blank=True, default='', help_text="Email of the administrator who finished the round. Blank for a round finished before this was recorded, which is never 'nobody'.", max_length=254),
        ),
    ]
