"""The Requests component picker stops naming one programme (2026-09-08).

⚠⚠ CHOICES-ONLY. THERE IS NO DDL — `sqlmigrate` prints nothing but a BEGIN/COMMIT pair. The column
is already `varchar(30)` and every stored VALUE is unchanged; only the human LABEL beside
`'applications'` moved from "B40 Applications" to "Applications". So the production step is the
`django_migrations` row and nothing else, applied migrate-first via Supabase MCP the way
`0113_alter_orgrequest_component` and `0116` were.

⚠ WHY IT EXISTS AT ALL: the menu row it names was renamed the same day, because the Applications
page lists whichever gift is chosen. A picker that still said "B40 Applications" would have sent an
org admin's bug report against a page name the console no longer uses. It was NOT found by a test —
it was found by reading the deployed bundle back and asking why the old string was still in it.
"""
# Generated by Django 5.2.15 on 2026-09-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0151_round_finished_for_good'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgrequest',
            name='component',
            field=models.CharField(blank=True, choices=[('applications', 'Applications'), ('applications_student_details', 'Student details'), ('applications_documents', 'Documents'), ('applications_ai_prediction', 'AI Prediction & verdicts'), ('applications_queries', 'Queries & blockers'), ('applications_interview', 'Interview'), ('applications_decision', 'Recommendation & QC'), ('applications_agreement', 'Bursary agreement'), ('applications_student_profile', 'Student profile (sponsor-facing)'), ('sponsors', 'Sponsors'), ('payments', 'Payments'), ('contracts', 'Contracts'), ('sources', 'Sources'), ('administration', 'Administration'), ('access', 'Sign-in & access'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
