# Generated by Django 5.2.15 on 2026-09-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """A REAL new table — unlike 0152, which was choices-only and needed a ledger row alone.

    ⚠ MIGRATE-FIRST, AND IT NEEDS RLS. `sqlmigrate` renders SQLite here, so hand-write the
    Postgres DDL against production before the push:

        CREATE TABLE scholarship_programme_code_aliases (
            id bigserial PRIMARY KEY,
            code varchar(50) NOT NULL UNIQUE,
            created_at timestamptz NOT NULL,
            created_by varchar(254) NOT NULL DEFAULT '',
            programme_id bigint NOT NULL
                REFERENCES scholarship_programmes(id) DEFERRABLE INITIALLY DEFERRED
        );
        CREATE INDEX scholarship_programme_code_aliases_programme_id_idx
            ON scholarship_programme_code_aliases (programme_id);
        ALTER TABLE scholarship_programme_code_aliases ENABLE ROW LEVEL SECURITY;
        CREATE POLICY service_role_all ON scholarship_programme_code_aliases
            FOR ALL TO service_role USING (true) WITH CHECK (true);

    Then record the `django_migrations` row. Every new table on this project carries RLS with
    exactly one service_role policy — the Security Advisor flags one that does not.

    NO BACKFILL. A gift that has never been renamed has no alias, and that is the correct
    state: an alias is written only by `AdminProgrammeDetailView.patch` when a code changes.
    """

    dependencies = [
        ('scholarship', '0152_alter_orgrequest_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeCodeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="A code this gift used to answer to, e.g. 'brightpath-flagship'.", max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, default='', help_text='Email of the admin who renamed the code, for the audit trail.', max_length=254)),
                ('programme', models.ForeignKey(help_text='The gift this retired code still points at.', on_delete=django.db.models.deletion.CASCADE, related_name='code_aliases', to='scholarship.programme')),
            ],
            options={
                'db_table': 'scholarship_programme_code_aliases',
                'ordering': ['programme_id', 'code'],
            },
        ),
    ]
