# Generated by Django 5.2.15 on 2026-09-10 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """TWO REAL NEW TABLES for sponsor spending reporting. Both need RLS.

    ⚠ MIGRATE-FIRST. `sqlmigrate` renders SQLite here, so hand-write the Postgres DDL against
    production BEFORE the push, then record the `django_migrations` row:

        CREATE TABLE merchant_categories (
            id bigserial PRIMARY KEY,
            merchant varchar(255) NOT NULL UNIQUE,
            category varchar(16) NOT NULL,
            decided_by varchar(16) NOT NULL,
            reason varchar(255) NOT NULL DEFAULT '',
            decided_at timestamptz NOT NULL,
            decided_by_email varchar(254) NOT NULL DEFAULT ''
        );
        ALTER TABLE merchant_categories ENABLE ROW LEVEL SECURITY;
        CREATE POLICY service_role_all ON merchant_categories
            FOR ALL TO service_role USING (true) WITH CHECK (true);

        CREATE TABLE bursary_spend_txns (
            id bigserial PRIMARY KEY,
            txn_id varchar(64) NOT NULL UNIQUE,
            txn_date date NOT NULL,
            wallet_id varchar(32) NOT NULL,
            merchant varchar(255) NOT NULL,
            amount numeric(10, 2) NOT NULL,
            duitnow_type varchar(64) NOT NULL DEFAULT '',
            entry_type varchar(16) NOT NULL DEFAULT '',
            tx_type varchar(16) NOT NULL DEFAULT '',
            status varchar(8) NOT NULL DEFAULT '',
            is_person_transfer boolean NOT NULL DEFAULT false,
            spender_is_child boolean NOT NULL DEFAULT false,
            category varchar(16) NOT NULL DEFAULT '',
            decided_by varchar(16) NOT NULL DEFAULT '',
            source_file varchar(255) NOT NULL DEFAULT '',
            imported_at timestamptz NOT NULL,
            application_id bigint NOT NULL
                REFERENCES scholarship_applications(id) DEFERRABLE INITIALLY DEFERRED
        );
        CREATE INDEX bursary_spend_txns_wallet_id_idx ON bursary_spend_txns (wallet_id);
        CREATE INDEX bursary_spend_txns_application_id_idx ON bursary_spend_txns (application_id);
        CREATE INDEX bursary_spend_txns_app_date_idx ON bursary_spend_txns (application_id, txn_date);
        CREATE INDEX bursary_spend_txns_merchant_idx ON bursary_spend_txns (merchant);
        ALTER TABLE bursary_spend_txns ENABLE ROW LEVEL SECURITY;
        CREATE POLICY service_role_all ON bursary_spend_txns
            FOR ALL TO service_role USING (true) WITH CHECK (true);

    ⚠ VERIFY THE REFERENCED TABLE NAME BEFORE RUNNING THE FK LINE. `ScholarshipApplication` sets
    its own `db_table`; confirm it is `scholarship_applications` on production rather than
    assuming the Django default. The 2026-06-01 `api_student_profiles` incident is the precedent —
    a bare ALTER against a guessed table name silently hit a real, different table.

    ⚠ EVERY NEW TABLE ON THIS PROJECT CARRIES RLS WITH EXACTLY ONE service_role POLICY. The
    Security Advisor flags one that does not; check it after applying.

    NO BACKFILL, AND NONE IS POSSIBLE. Both tables are filled by `ingest_spending`, which reads
    the Vircle exports. There is no earlier data to recover: the corpus IS the history.
    """

    dependencies = [
        ('scholarship', '0154_programme_apply_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('food', 'Food & drink'), ('groceries', 'Groceries'), ('transport', 'Transport'), ('study', 'Books & study supplies'), ('phone', 'Phone & internet'), ('hostel', 'Hostel & bills'), ('health', 'Health & pharmacy'), ('clothing', 'Clothing & shoes'), ('transfer', 'Sent to a person'), ('unsorted', 'Not yet sorted')], max_length=16)),
                ('decided_by', models.CharField(choices=[('', 'Not yet decided'), ('duitnow', 'From the DuitNow type'), ('rule', 'From the merchant name'), ('inferred', 'Inferred from the spending pattern'), ('ai', 'Decided by the model'), ('owner', 'Set by a person')], max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('decided_at', models.DateTimeField(auto_now=True)),
                ('decided_by_email', models.CharField(blank=True, default='', help_text="Set only when decided_by='owner' - the audit trail for a human correction.", max_length=254)),
            ],
            options={
                'db_table': 'merchant_categories',
                'ordering': ['merchant'],
            },
        ),
        migrations.CreateModel(
            name='BursarySpendTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(help_text="Vircle's own transaction id - the idempotency key.", max_length=64, unique=True)),
                ('txn_date', models.DateField(help_text='Date only. The time of day is discarded at import: newer reports no longer carry it, and no sponsor may ever see what hour a student ate.')),
                ('wallet_id', models.CharField(db_index=True, max_length=32)),
                ('merchant', models.CharField(help_text='The shop, upper-cased and whitespace-collapsed. NEVER shown to a sponsor.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duitnow_type', models.CharField(blank=True, default='', max_length=64)),
                ('entry_type', models.CharField(blank=True, default='', max_length=16)),
                ('tx_type', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(blank=True, default='', max_length=8)),
                ('is_person_transfer', models.BooleanField(default=False)),
                ('spender_is_child', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, choices=[('food', 'Food & drink'), ('groceries', 'Groceries'), ('transport', 'Transport'), ('study', 'Books & study supplies'), ('phone', 'Phone & internet'), ('hostel', 'Hostel & bills'), ('health', 'Health & pharmacy'), ('clothing', 'Clothing & shoes'), ('transfer', 'Sent to a person'), ('unsorted', 'Not yet sorted')], default='', help_text="Blank until the sorter runs; 'unsorted' means it ran and could not place it. The two are different states and must not be collapsed.", max_length=16)),
                ('decided_by', models.CharField(blank=True, choices=[('', 'Not yet decided'), ('duitnow', 'From the DuitNow type'), ('rule', 'From the merchant name'), ('inferred', 'Inferred from the spending pattern'), ('ai', 'Decided by the model'), ('owner', 'Set by a person')], default='', max_length=16)),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(help_text='Resolved from wallet_id. A row whose wallet matches no student is NOT stored - it is reported, because money filed against nobody is worse than money we have flagged.', on_delete=django.db.models.deletion.PROTECT, related_name='spend_txns', to='scholarship.scholarshipapplication')),
            ],
            options={
                'db_table': 'bursary_spend_txns',
                'ordering': ['-txn_date', '-id'],
                'indexes': [models.Index(fields=['application', 'txn_date'], name='bursary_spe_applica_22d352_idx'), models.Index(fields=['merchant'], name='bursary_spe_merchan_d55715_idx')],
            },
        ),
    ]
