# Generated by Django 5.2.15 on 2026-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0155_spending_txns'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='ai_verdict_engine_version',
            field=models.CharField(blank=True, default='', help_text="The verdict_engine version that produced ai_verdict_snapshot. 'pre-versioning' = decided before this was recorded. Empty = never decided.", max_length=32),
        ),
    ]
