# Generated by Django 5.2.15 on 2026-09-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0074_organisationconfiguration'),
        ('scholarship', '0156_verdict_engine_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcost',
            name='source',
            field=models.CharField(choices=[('gcp', 'Google Cloud Platform'), ('supabase', 'Supabase'), ('workspace', 'Google Workspace'), ('brevo', 'Brevo'), ('twilio', 'Twilio'), ('other', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrgBillingAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.CharField(help_text="The single month this applies to, 'YYYY-MM'. Never a range: a waiver that rolls forward on its own is how an unbilled year happens.", max_length=7)),
                ('discount_pct', models.DecimalField(decimal_places=2, help_text='Percent off the computed charge. 100 = the month is shown in full and charged nothing. Decimal, never float — this lands on an invoice.', max_digits=5)),
                ('reason', models.TextField(help_text='REQUIRED. Why this month was discounted, in words a stranger reading the ledger next year can act on.')),
                ('set_by_email', models.EmailField(blank=True, default='', help_text='Who decided it. Waiving a charge is a commercial act and needs a name.', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(help_text='The tenant whose bill is reduced. PROTECT: a billing decision must outlive any tidy-up of the organisation record.', on_delete=django.db.models.deletion.PROTECT, related_name='billing_adjustments', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'org_billing_adjustments',
                'ordering': ['-period_month', 'organisation'],
                'constraints': [models.UniqueConstraint(fields=('organisation', 'period_month'), name='org_billing_adjustment_unique_month')],
            },
        ),
    ]
