# Generated by Django 5.2.15 on 2026-09-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0157_extracted_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcost',
            name='source',
            field=models.CharField(choices=[('gcp', 'Google Cloud Platform'), ('supabase', 'Supabase'), ('workspace', 'Google Workspace'), ('brevo', 'Brevo'), ('twilio', 'Twilio'), ('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI'), ('cloudflare', 'Cloudflare'), ('github', 'GitHub'), ('other', 'Other')], max_length=20),
        ),
    ]
