# Generated by Django 5.2.15 on 2026-09-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0157_billing_adjustment_and_workspace_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformcost',
            name='provenance',
            field=models.CharField(choices=[('measured', "Measured — pulled from the provider's own billing data"), ('extracted', "Extracted — parsed from the provider's own invoice, reconciled to its printed total"), ('entered', 'Entered by hand from an invoice')], max_length=10),
        ),
    ]
