"""Tenant invoices and receipts (2026-09-14).

ADDITIVE: six new tables, no change to any existing column.

⚠ MIGRATE-FIRST via Supabase MCP before the push, then record the `django_migrations` row
(scholarship ledger 159 → 160). `sqlmigrate` renders SQLite on a dev box, so this is the Postgres
DDL that was run, verbatim — generated offline from this migration with the postgres backend:

    CREATE TABLE "invoice_issuer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "legal_name" varchar(200) NOT NULL, "registration_no" varchar(60) NOT NULL, "address" text NOT NULL, "email" varchar(254) NOT NULL, "phone" varchar(30) NOT NULL, "bank_name" varchar(120) NOT NULL, "bank_account_name" varchar(200) NOT NULL, "bank_account_no" varchar(40) NOT NULL, "payment_terms_days" smallint NOT NULL CHECK ("payment_terms_days" >= 0), "updated_by_email" varchar(254) NOT NULL, "updated_at" timestamp with time zone NOT NULL);
    CREATE TABLE "billing_sequences" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "kind" varchar(3) NOT NULL, "year" smallint NOT NULL CHECK ("year" >= 0), "last" integer NOT NULL CHECK ("last" >= 0), CONSTRAINT "billing_sequence_unique" UNIQUE ("kind", "year"));
    CREATE TABLE "invoices" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "number" varchar(20) NOT NULL UNIQUE, "period_month" varchar(7) NOT NULL, "issued_on" date NOT NULL, "due_on" date NOT NULL, "currency" varchar(3) NOT NULL, "subtotal_myr" numeric(12, 2) NOT NULL, "discount_pct" numeric(5, 2) NOT NULL, "discount_myr" numeric(12, 2) NOT NULL, "discount_reason" text NOT NULL, "total_myr" numeric(12, 2) NOT NULL, "issuer_snapshot" jsonb NOT NULL, "bill_to_snapshot" jsonb NOT NULL, "issued_by_email" varchar(254) NOT NULL, "override_reason" text NOT NULL, "sent_at" timestamp with time zone NULL, "sent_by_email" varchar(254) NOT NULL, "sent_to" jsonb NOT NULL, "voided_at" timestamp with time zone NULL, "voided_by_email" varchar(254) NOT NULL, "void_reason" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "organisation_id" bigint NOT NULL, "replaces_id" bigint NULL);
    CREATE TABLE "invoice_lines" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "position" smallint NOT NULL CHECK ("position" >= 0), "category" varchar(20) NOT NULL, "description" varchar(300) NOT NULL, "quantity" numeric(8, 1) NULL, "unit_amount_myr" numeric(10, 2) NULL, "amount_myr" numeric(12, 2) NOT NULL, "invoice_id" bigint NOT NULL);
    CREATE TABLE "invoice_receipts" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "number" varchar(20) NOT NULL UNIQUE, "received_on" date NOT NULL, "amount_myr" numeric(12, 2) NOT NULL, "method" varchar(20) NOT NULL, "reference" varchar(120) NOT NULL, "note" text NOT NULL, "recorded_by_email" varchar(254) NOT NULL, "created_at" timestamp with time zone NOT NULL, "invoice_id" bigint NOT NULL);
    CREATE TABLE "org_billing_details" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "bill_to_name" varchar(200) NOT NULL, "address" text NOT NULL, "emails" jsonb NOT NULL, "updated_by_email" varchar(254) NOT NULL, "updated_at" timestamp with time zone NOT NULL, "organisation_id" bigint NOT NULL UNIQUE);
    CREATE INDEX "invoice_org_month_idx" ON "invoices" ("organisation_id", "period_month");
    CREATE UNIQUE INDEX "invoice_one_live_per_org_month" ON "invoices" ("organisation_id", "period_month") WHERE "voided_at" IS NULL;
    ALTER TABLE "invoices" ADD CONSTRAINT "invoices_organisation_id_a5bd7047_fk_partner_organisations_id" FOREIGN KEY ("organisation_id") REFERENCES "partner_organisations" ("id") DEFERRABLE INITIALLY DEFERRED;
    ALTER TABLE "invoices" ADD CONSTRAINT "invoices_replaces_id_1054c8eb_fk_invoices_id" FOREIGN KEY ("replaces_id") REFERENCES "invoices" ("id") DEFERRABLE INITIALLY DEFERRED;
    CREATE INDEX "invoices_number_6197e1da_like" ON "invoices" ("number" varchar_pattern_ops);
    CREATE INDEX "invoices_organisation_id_a5bd7047" ON "invoices" ("organisation_id");
    CREATE INDEX "invoices_replaces_id_1054c8eb" ON "invoices" ("replaces_id");
    ALTER TABLE "invoice_lines" ADD CONSTRAINT "invoice_lines_invoice_id_9a48de71_fk_invoices_id" FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") DEFERRABLE INITIALLY DEFERRED;
    CREATE INDEX "invoice_lines_invoice_id_9a48de71" ON "invoice_lines" ("invoice_id");
    ALTER TABLE "invoice_receipts" ADD CONSTRAINT "invoice_receipts_invoice_id_7be6aa58_fk_invoices_id" FOREIGN KEY ("invoice_id") REFERENCES "invoices" ("id") DEFERRABLE INITIALLY DEFERRED;
    CREATE INDEX "invoice_receipts_number_a55df497_like" ON "invoice_receipts" ("number" varchar_pattern_ops);
    CREATE INDEX "invoice_receipts_invoice_id_7be6aa58" ON "invoice_receipts" ("invoice_id");
    ALTER TABLE "org_billing_details" ADD CONSTRAINT "org_billing_details_organisation_id_7f19e200_fk_partner_o" FOREIGN KEY ("organisation_id") REFERENCES "partner_organisations" ("id") DEFERRABLE INITIALLY DEFERRED;
    ALTER TABLE public.invoice_issuer ENABLE ROW LEVEL SECURITY;
    CREATE POLICY invoice_issuer_service_role ON public.invoice_issuer FOR ALL TO service_role USING (true) WITH CHECK (true);
    ALTER TABLE public.billing_sequences ENABLE ROW LEVEL SECURITY;
    CREATE POLICY billing_sequences_service_role ON public.billing_sequences FOR ALL TO service_role USING (true) WITH CHECK (true);
    ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
    CREATE POLICY invoices_service_role ON public.invoices FOR ALL TO service_role USING (true) WITH CHECK (true);
    ALTER TABLE public.invoice_lines ENABLE ROW LEVEL SECURITY;
    CREATE POLICY invoice_lines_service_role ON public.invoice_lines FOR ALL TO service_role USING (true) WITH CHECK (true);
    ALTER TABLE public.invoice_receipts ENABLE ROW LEVEL SECURITY;
    CREATE POLICY invoice_receipts_service_role ON public.invoice_receipts FOR ALL TO service_role USING (true) WITH CHECK (true);
    ALTER TABLE public.org_billing_details ENABLE ROW LEVEL SECURITY;
    CREATE POLICY org_billing_details_service_role ON public.org_billing_details FOR ALL TO service_role USING (true) WITH CHECK (true);
    ALTER TABLE public.org_billing_adjustments ENABLE ROW LEVEL SECURITY;
    CREATE POLICY org_billing_adjustments_service_role ON public.org_billing_adjustments FOR ALL TO service_role USING (true) WITH CHECK (true);

RLS in the SAME step as the CREATE — the house convention (deny by default, one service_role
policy). ⚠ `org_billing_adjustments` (migration 0157) had shipped WITHOUT it and the Security
Advisor flagged it as an ERROR (readable with the publishable key); its RLS was switched on in
this same step. Invoices carry bank account numbers and addresses, so a table here without RLS
would be the same exposure with worse contents.
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0074_organisationconfiguration'),
        ('scholarship', '0159_more_cost_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, default='', max_length=200)),
                ('registration_no', models.CharField(blank=True, default='', help_text='Company or society registration number, when one exists. Printed if set.', max_length=60)),
                ('address', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', help_text='Printed on the invoice and used as the reply-to on Send.', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=40)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30, help_text='Days from the issue date to the due date. Snapshotted: changing it never moves the due date of an invoice already issued.')),
                ('updated_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_issuer',
            },
        ),
        migrations.CreateModel(
            name='BillingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('last', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_sequences',
                'constraints': [models.UniqueConstraint(fields=('kind', 'year'), name='billing_sequence_unique')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="'INV-YYYY-NNNN', numbered by the year of issue.", max_length=20, unique=True)),
                ('period_month', models.CharField(help_text="The month billed, 'YYYY-MM'.", max_length=7)),
                ('issued_on', models.DateField()),
                ('due_on', models.DateField()),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('subtotal_myr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_reason', models.TextField(blank=True, default='')),
                ('total_myr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issuer_snapshot', models.JSONField(default=dict)),
                ('bill_to_snapshot', models.JSONField(default=dict)),
                ('issued_by_email', models.EmailField(blank=True, default='', help_text='Blank = issued by the monthly job on the 15th.', max_length=254)),
                ('override_reason', models.TextField(blank=True, default='', help_text='Set only when a super issued it despite a readiness warning — the warning and why it was overridden, so the decision survives the person who made it.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sent_to', models.JSONField(blank=True, default=list)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('voided_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='courses.partnerorganisation')),
                ('replaces', models.ForeignKey(blank=True, help_text='The voided invoice this one was issued to replace.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='scholarship.invoice')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-period_month', '-issued_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('infrastructure', 'Platform infrastructure'), ('metered', 'Metered usage'), ('development', 'Development')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(blank=True, decimal_places=1, help_text='Hours, for development. Null for the two cost-share lines.', max_digits=8, null=True)),
                ('unit_amount_myr', models.DecimalField(blank=True, decimal_places=2, help_text='The BILLED hourly rate (margin included), so quantity x unit = amount.', max_digits=10, null=True)),
                ('amount_myr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scholarship.invoice')),
            ],
            options={
                'db_table': 'invoice_lines',
                'ordering': ['invoice', 'position'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="'RCP-YYYY-NNNN', numbered by the year received.", max_length=20, unique=True)),
                ('received_on', models.DateField()),
                ('amount_myr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('recorded_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='scholarship.invoice')),
            ],
            options={
                'db_table': 'invoice_receipts',
                'ordering': ['invoice', 'received_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrgBillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_to_name', models.CharField(blank=True, default='', help_text='The name printed under "Bill to" — the legal name, which may differ from the display name the platform uses.', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('emails', models.JSONField(blank=True, default=list, help_text='Where Send delivers the invoice. A list: finance inboxes are often two people.')),
                ('updated_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_details', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'org_billing_details',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organisation', 'period_month'], name='invoice_org_month_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('organisation', 'period_month'), name='invoice_one_live_per_org_month'),
        ),
    ]
