# Generated by Django 5.2.15 on 2026-09-14 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0074_organisationconfiguration'),
        ('scholarship', '0159_more_cost_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceIssuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, default='', max_length=200)),
                ('registration_no', models.CharField(blank=True, default='', help_text='Company or society registration number, when one exists. Printed if set.', max_length=60)),
                ('address', models.TextField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', help_text='Printed on the invoice and used as the reply-to on Send.', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('bank_name', models.CharField(blank=True, default='', max_length=120)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_no', models.CharField(blank=True, default='', max_length=40)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30, help_text='Days from the issue date to the due date. Snapshotted: changing it never moves the due date of an invoice already issued.')),
                ('updated_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_issuer',
            },
        ),
        migrations.CreateModel(
            name='BillingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=3)),
                ('year', models.PositiveSmallIntegerField()),
                ('last', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'billing_sequences',
                'constraints': [models.UniqueConstraint(fields=('kind', 'year'), name='billing_sequence_unique')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="'INV-YYYY-NNNN', numbered by the year of issue.", max_length=20, unique=True)),
                ('period_month', models.CharField(help_text="The month billed, 'YYYY-MM'.", max_length=7)),
                ('issued_on', models.DateField()),
                ('due_on', models.DateField()),
                ('currency', models.CharField(default='MYR', max_length=3)),
                ('subtotal_myr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_myr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_reason', models.TextField(blank=True, default='')),
                ('total_myr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issuer_snapshot', models.JSONField(default=dict)),
                ('bill_to_snapshot', models.JSONField(default=dict)),
                ('issued_by_email', models.EmailField(blank=True, default='', help_text='Blank = issued by the monthly job on the 15th.', max_length=254)),
                ('override_reason', models.TextField(blank=True, default='', help_text='Set only when a super issued it despite a readiness warning — the warning and why it was overridden, so the decision survives the person who made it.')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sent_to', models.JSONField(blank=True, default=list)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('voided_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('void_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='courses.partnerorganisation')),
                ('replaces', models.ForeignKey(blank=True, help_text='The voided invoice this one was issued to replace.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replaced_by', to='scholarship.invoice')),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-period_month', '-issued_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('infrastructure', 'Platform infrastructure'), ('metered', 'Metered usage'), ('development', 'Development')], max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.DecimalField(blank=True, decimal_places=1, help_text='Hours, for development. Null for the two cost-share lines.', max_digits=8, null=True)),
                ('unit_amount_myr', models.DecimalField(blank=True, decimal_places=2, help_text='The BILLED hourly rate (margin included), so quantity x unit = amount.', max_digits=10, null=True)),
                ('amount_myr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='scholarship.invoice')),
            ],
            options={
                'db_table': 'invoice_lines',
                'ordering': ['invoice', 'position'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text="'RCP-YYYY-NNNN', numbered by the year received.", max_length=20, unique=True)),
                ('received_on', models.DateField()),
                ('amount_myr', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('reference', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('recorded_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='scholarship.invoice')),
            ],
            options={
                'db_table': 'invoice_receipts',
                'ordering': ['invoice', 'received_on', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrgBillingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_to_name', models.CharField(blank=True, default='', help_text='The name printed under "Bill to" — the legal name, which may differ from the display name the platform uses.', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('emails', models.JSONField(blank=True, default=list, help_text='Where Send delivers the invoice. A list: finance inboxes are often two people.')),
                ('updated_by_email', models.EmailField(blank=True, default='', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='billing_details', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'org_billing_details',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organisation', 'period_month'], name='invoice_org_month_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('voided_at__isnull', True)), fields=('organisation', 'period_month'), name='invoice_one_live_per_org_month'),
        ),
    ]
