"""The organisation's Overview layout (Programme Overview phase 2, 2026-09-18).

ADDITIVE: one new table, no change to any existing column.

⚠ MIGRATE-FIRST via Supabase MCP before the push, then record the `django_migrations` row
(scholarship ledger 160 → 161). `sqlmigrate` renders SQLite on a dev box, so this is the Postgres
DDL to run, verbatim — generated offline from this migration with the postgres backend:

    CREATE TABLE "organisation_overview_layouts" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "sections" jsonb NOT NULL, "updated_by_email" varchar(254) NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "organisation_id" bigint NOT NULL UNIQUE);
    ALTER TABLE "organisation_overview_layouts" ADD CONSTRAINT "organisation_overview_l_organisation_id_2d4f6b1a_fk_partner_o" FOREIGN KEY ("organisation_id") REFERENCES "partner_organisations" ("id") DEFERRABLE INITIALLY DEFERRED;
    ALTER TABLE public.organisation_overview_layouts ENABLE ROW LEVEL SECURITY;
    CREATE POLICY organisation_overview_layouts_service_role ON public.organisation_overview_layouts FOR ALL TO service_role USING (true) WITH CHECK (true);

RLS in the SAME step as the CREATE — the house convention (deny by default, one service_role
policy); the 0160 docstring records why (`org_billing_adjustments` shipped without it and the
Security Advisor flagged it). The row holds no person and no money, but the convention is the
convention: every table, no exceptions to remember.
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0074_organisationconfiguration'),
        ('scholarship', '0160_tenant_invoices'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationOverviewLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sections', models.JSONField(default=list, help_text='Ordered list of {key, on} over the five customisable Overview widgets.')),
                ('updated_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview_layout', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'organisation_overview_layouts',
            },
        ),
    ]
