"""Request #26 (2026-10-05): the change record for the parent/guardian contact.

ADDITIVE: one new table, no change to any existing column. The contact itself does NOT move — it
stays entry 0 of `api_student_profiles.guardians` — and nothing is backfilled (owner ruling R7).

⚠ MIGRATE-FIRST via Supabase MCP before the push, then record the `django_migrations` row
(scholarship ledger 164 → 165). `sqlmigrate` renders SQLite on a dev box, so this is the Postgres
DDL to run, verbatim — generated offline from this migration with the postgres backend:

    CREATE TABLE "guardian_contact_changes" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "old_name" varchar(255) NOT NULL, "new_name" varchar(255) NOT NULL, "old_phone" varchar(32) NOT NULL, "new_phone" varchar(32) NOT NULL, "changed_by_email" varchar(254) NOT NULL, "changed_by_role" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "application_id" bigint NULL, "profile_id" varchar(100) NOT NULL);
    ALTER TABLE "guardian_contact_changes" ADD CONSTRAINT "guardian_contact_cha_application_id_9b12927f_fk_scholarsh" FOREIGN KEY ("application_id") REFERENCES "scholarship_applications" ("id") DEFERRABLE INITIALLY DEFERRED;
    ALTER TABLE "guardian_contact_changes" ADD CONSTRAINT "guardian_contact_cha_profile_id_b947b872_fk_api_stude" FOREIGN KEY ("profile_id") REFERENCES "api_student_profiles" ("supabase_user_id") DEFERRABLE INITIALLY DEFERRED;
    CREATE INDEX "guardian_contact_changes_application_id_9b12927f" ON "guardian_contact_changes" ("application_id");
    CREATE INDEX "guardian_contact_changes_profile_id_b947b872" ON "guardian_contact_changes" ("profile_id");
    CREATE INDEX "guardian_contact_changes_profile_id_b947b872_like" ON "guardian_contact_changes" ("profile_id" varchar_pattern_ops);
    ALTER TABLE public.guardian_contact_changes ENABLE ROW LEVEL SECURITY;
    CREATE POLICY guardian_contact_changes_service_role ON public.guardian_contact_changes FOR ALL TO service_role USING (true) WITH CHECK (true);

RLS in the SAME step as the CREATE — the house convention (deny by default, one service_role
policy; see 0160). This table holds a parent's name and phone, so it matters here more than most.

⚠ BETWEEN MIGRATE AND DEPLOY the image already serving never reads or writes this table, so the
order is safe. Deploying BEFORE migrating is not: every guardian-contact save would 500.
"""
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0076_spm_prereq_selection'),
        ('scholarship', '0164_contracttemplate_programme_not_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianContactChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_name', models.CharField(blank=True, default='', max_length=255)),
                ('new_name', models.CharField(blank=True, default='', max_length=255)),
                ('old_phone', models.CharField(blank=True, default='', max_length=32)),
                ('new_phone', models.CharField(blank=True, default='', max_length=32)),
                ('changed_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('changed_by_role', models.CharField(choices=[('student', 'Student'), ('admin', 'Administrator')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_contact_changes', to='scholarship.scholarshipapplication')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_contact_changes', to='courses.studentprofile')),
            ],
            options={
                'db_table': 'guardian_contact_changes',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
