# Generated by Django 5.2.15 on 2026-10-05 15:18
"""A person-only spending category, `micro_stall` (request #28, 2026-10-06).

⚠ **NO DATABASE WORK AT ALL.** Both `AlterField`s are choices-only — `max_length`, default and
help text are unchanged — and `sqlmigrate` prints `(no-op)` for each (Django choices are validated
in Python, never as a Postgres constraint). The production step is the `django_migrations` ledger
row alone. No data moves; existing rows keep their categories.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0165_guardian_contact_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bursaryspendtxn',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food & drink'), ('groceries', 'Groceries'), ('transport', 'Transport'), ('study', 'Books & study supplies'), ('phone', 'Phone & internet'), ('hostel', 'Hostel & bills'), ('health', 'Health & pharmacy'), ('clothing', 'Clothing & shoes'), ('micro_stall', 'Micro stall – no online info'), ('transfer', 'Sent to a person'), ('unsorted', 'Not yet sorted')], default='', help_text="Blank until the sorter runs; 'unsorted' means it ran and could not place it. The two are different states and must not be collapsed.", max_length=16),
        ),
        migrations.AlterField(
            model_name='merchantcategory',
            name='category',
            field=models.CharField(choices=[('food', 'Food & drink'), ('groceries', 'Groceries'), ('transport', 'Transport'), ('study', 'Books & study supplies'), ('phone', 'Phone & internet'), ('hostel', 'Hostel & bills'), ('health', 'Health & pharmacy'), ('clothing', 'Clothing & shoes'), ('micro_stall', 'Micro stall – no online info'), ('transfer', 'Sent to a person'), ('unsorted', 'Not yet sorted')], max_length=16),
        ),
    ]
