# Generated by Django 5.2.15 on 2026-10-06 08:55
"""A closure reason, `stalled` (TD-352, 2026-10-06): an officer closes an application that stopped
moving, so the student may apply again.

⚠ **NO DATABASE WORK AT ALL.** The `AlterField` is choices-only — `max_length`, default and help
text are unchanged — and `sqlmigrate` prints `(no-op)` (Django choices are validated in Python,
never as a Postgres constraint). The production step is the `django_migrations` ledger row alone.
No data moves; existing rows keep their reasons.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0166_spend_category_micro_stall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarshipapplication',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('graduated', 'Graduated — completed the programme'), ('completed', 'Completed the contractual support period'), ('withdrawn', 'Withdrawn by the student'), ('lapsed', 'Lapsed — support stopped (fell away)'), ('terminated', 'Terminated for cause'), ('stalled', 'No movement — closed by an officer')], default='', help_text="Why the application reached status='closed'; blank unless status='closed'", max_length=20),
        ),
    ]
