# Generated by Django 5.2.15 on 2026-10-06 02:04
"""Request #28 follow-up (2026-10-06): a shop flagged for review by ONE organisation, and its notes
log — `merchant_flags` and `merchant_flag_notes`.

ADDITIVE: two new tables, no change to any existing column, nothing backfilled. A flag never moves a
category or a total; no existing reader reads these tables.

⚠ MIGRATE-FIRST via Supabase MCP before the push, then record the `django_migrations` row
(scholarship ledger 166 → 167). `sqlmigrate` renders SQLite on a dev box, so this is the Postgres
DDL to run, verbatim — rendered offline from this migration with the postgresql backend (no
connection), then the house RLS convention added by hand:

    CREATE TABLE "merchant_flags" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "merchant" varchar(255) NOT NULL, "is_open" boolean NOT NULL, "opened_at" timestamp with time zone NOT NULL, "opened_by_email" varchar(254) NOT NULL, "closed_at" timestamp with time zone NULL, "closed_by_email" varchar(254) NOT NULL, "organisation_id" bigint NOT NULL);
    CREATE TABLE "merchant_flag_notes" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "kind" varchar(8) NOT NULL, "body" varchar(2000) NOT NULL, "author_email" varchar(254) NOT NULL, "created_at" timestamp with time zone NOT NULL, "flag_id" bigint NOT NULL);
    ALTER TABLE "merchant_flags" ADD CONSTRAINT "merchant_flag_one_per_org_shop" UNIQUE ("organisation_id", "merchant");
    ALTER TABLE "merchant_flag_notes" ADD CONSTRAINT "merchant_flag_note_not_blank" CHECK (NOT ("body" = ''));
    ALTER TABLE "merchant_flags" ADD CONSTRAINT "merchant_flags_organisation_id_a6c32315_fk_partner_o" FOREIGN KEY ("organisation_id") REFERENCES "partner_organisations" ("id") DEFERRABLE INITIALLY DEFERRED;
    CREATE INDEX "merchant_flags_organisation_id_a6c32315" ON "merchant_flags" ("organisation_id");
    ALTER TABLE "merchant_flag_notes" ADD CONSTRAINT "merchant_flag_notes_flag_id_a251d294_fk_merchant_flags_id" FOREIGN KEY ("flag_id") REFERENCES "merchant_flags" ("id") DEFERRABLE INITIALLY DEFERRED;
    CREATE INDEX "merchant_flag_notes_flag_id_a251d294" ON "merchant_flag_notes" ("flag_id");
    ALTER TABLE public.merchant_flags ENABLE ROW LEVEL SECURITY;
    CREATE POLICY merchant_flags_service_role ON public.merchant_flags FOR ALL TO service_role USING (true) WITH CHECK (true);
    ALTER TABLE public.merchant_flag_notes ENABLE ROW LEVEL SECURITY;
    CREATE POLICY merchant_flag_notes_service_role ON public.merchant_flag_notes FOR ALL TO service_role USING (true) WITH CHECK (true);
    INSERT INTO django_migrations (app, name, applied) VALUES ('scholarship', '0167_merchant_flags', now());

⚠ ON DELETE PROTECT (both foreign keys) is enforced by DJANGO, not by this DDL — Django never emits
ON DELETE clauses; the plain FK already refuses a raw delete of a referenced row.

RLS in the SAME step as the CREATE — the house convention (ENABLE, not FORCE; one service_role
policy; see 0160 and 0165). The `rls_auto_enable` event trigger would switch RLS on anyway, but it
adds no policy. These tables hold one organisation's private notes about shops its students used:
nothing outside Django may read them. Run the Security Advisor after applying.

⚠ BETWEEN MIGRATE AND DEPLOY the image already serving never reads or writes these tables, so the
order is safe. Deploying BEFORE migrating is not: the spending screen would 500 on every load.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0076_spm_prereq_selection'),
        ('scholarship', '0166_spend_category_micro_stall'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant', models.CharField(max_length=255)),
                ('is_open', models.BooleanField(default=True)),
                ('opened_at', models.DateTimeField()),
                ('opened_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_email', models.CharField(blank=True, default='', max_length=254)),
                ('organisation', models.ForeignKey(help_text='The ONE organisation this flag belongs to. Never shown to any other.', on_delete=django.db.models.deletion.PROTECT, related_name='merchant_flags', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'merchant_flags',
            },
        ),
        migrations.CreateModel(
            name='MerchantFlagNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('open', 'Flagged'), ('note', 'Note'), ('close', 'Cleared')], max_length=8)),
                ('body', models.CharField(max_length=2000)),
                ('author_email', models.CharField(blank=True, default='', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='scholarship.merchantflag')),
            ],
            options={
                'db_table': 'merchant_flag_notes',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='merchantflag',
            constraint=models.UniqueConstraint(fields=('organisation', 'merchant'), name='merchant_flag_one_per_org_shop'),
        ),
        migrations.AddConstraint(
            model_name='merchantflagnote',
            constraint=models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='merchant_flag_note_not_blank'),
        ),
    ]
