# Generated by Django 5.2.15 on 2026-10-06 09:06
"""Request #30 (2026-10-06): an intake year can require a minimum number of SPM grades at C or
better — `ScholarshipCohort.min_spm_credit_count`.

ADDITIVE: one nullable column, NO DEFAULT, nothing backfilled. It arrives NULL on every existing
intake year, and NULL means the test is not applied (the value IS the switch — Sabah S2a), so
nobody's eligibility changes until an admin types a number.

⚠ MIGRATE-FIRST via Supabase MCP before the push, then record the `django_migrations` row
(scholarship ledger 167 → 168). `sqlmigrate` renders SQLite on a dev box, so this is the Postgres
DDL to run, verbatim — rendered offline from this migration with the postgresql backend's schema
editor (no connection):

    ALTER TABLE "scholarship_cohorts" ADD COLUMN "min_spm_credit_count" integer NULL;
    INSERT INTO django_migrations (app, name, applied) VALUES ('scholarship', '0169_cohort_min_spm_credit_count', now());

No RLS step: a column on an existing table inherits that table's policies.

⚠ BETWEEN MIGRATE AND DEPLOY the image already serving never reads this column, so the order is
safe. Deploying BEFORE migrating is not: the new image selects this column on EVERY load of an
intake year (Django selects every field), so submissions, the apply page and the console would 500.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0168_closure_reason_stalled'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipcohort',
            name='min_spm_credit_count',
            field=models.IntegerField(blank=True, help_text="Minimum SPM grades at C or better (A+ to C; SPM has no C-) — the TOTAL credit count, A's and B's included, so 8 A's and no C's clear a floor of 6. NULL = not applied.", null=True),
        ),
    ]
