# Generated by Django 5.2.15 on 2026-10-06 18:54
"""org-timing Sprint 1, review finding F1 (owner option 1, 2026-10-07): keep the promise the final
reminder makes — `ScholarshipApplication.final_reminder_close_days`.

The final completion reminder (R4) tells the student "complete within N days or we close it", and
N is now an organisation setting (`auto_close_after_final_reminder_days`). The sweep stamps the N it
stated in the same save that records R4, and the close waits the LONGER of that and the current
setting, so an organisation lowering the setting can never close a warned student early.

ADDITIVE: one nullable column, NO DEFAULT, nothing backfilled. NULL = a final reminder sent before
this column existed; those reminders said the literal "5", and the sweep reads NULL as 5.

⚠ MIGRATE-FIRST via Supabase MCP before the push, then record the `django_migrations` row. This is
the Postgres DDL to run, verbatim — rendered offline from this migration with the postgresql
backend's schema editor (no connection):

    ALTER TABLE "scholarship_applications" ADD COLUMN "final_reminder_close_days" smallint NULL CHECK ("final_reminder_close_days" >= 0);
    INSERT INTO django_migrations (app, name, applied) VALUES ('scholarship', '0170_application_final_reminder_close_days', now());

No RLS step: a column on an existing table inherits that table's policies.

⚠ BETWEEN MIGRATE AND DEPLOY the image already serving never reads this column, so the order is
safe. Deploying BEFORE migrating is not: Django selects every field of an application on every
load, so nearly every route would 500.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0169_cohort_min_spm_credit_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarshipapplication',
            name='final_reminder_close_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Days the FINAL reminder STATED before closing; the close never comes sooner (NULL = 5)', null=True),
        ),
    ]
