# Generated by Django 5.2.15 on 2026-10-08 11:56
"""Per-gift referral sources, Sprint 1 (owner, 2026-10-08): each gift chooses its own set of
referral sources — `programme_referral_sources`, one row per (gift, source) on that gift's form.

ADDITIVE: one new table plus its seed. `PartnerOrganisation.programme` (the old single-gift FK)
is NOT dropped here — expand-contract; it is deprecated, no longer read or written, and its drop
is a later migration.

THE SEED (`seed_programme_sources`, below — a test calls it on a production-shaped fixture):
every ACTIVE gift gets every ACTIVE source — `show_in_apply` AND `is_active` AND not a tenant
(owns an active gift, or has an active `org_admin`; the same two tests as
`PartnerOrganisationQuerySet.tenants()`, spelled out because a migration's historical model has
no custom queryset). EXCEPT a source whose old `programme` FK is set: that source goes on that
ONE gift only, which is what the FK meant. Production on 2026-10-08: 7 active sources, none with
a gift set, 2 active gifts (`brightpath-flagship`, `bpb-sabah-2026`) and 1 inactive (`testing`)
→ 14 rows. Reverse deletes every row (the table is new, so every row is the seed's or later).

⚠ MIGRATE-FIRST via Supabase MCP before the push. The Postgres SQL — the DDL rendered offline
with the postgresql backend, the house RLS step, the seed as one INSERT … SELECT and the ledger
row, in ONE transaction — is `docs/scholarship/gift-sources-s1-cutover-sql.md`. Do not paste
`sqlmigrate` (it renders SQLite here).

⚠ BETWEEN MIGRATE AND DEPLOY the image already serving never reads this table, so the order is
safe. Deploying BEFORE migrating is not: the gift Configuration screen and the Sources list read
it on every load and would 500.
"""

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Exists, OuterRef, Q


def seed_programme_sources(apps, schema_editor):
    """Link every active gift to every active source; a source with a gift set → that gift only.

    Takes an app registry so a test can run it against the live models (`django.apps.apps`) on a
    production-shaped fixture. Idempotent: an existing (gift, source) row is left alone.
    """
    Programme = apps.get_model('scholarship', 'Programme')
    PartnerOrganisation = apps.get_model('courses', 'PartnerOrganisation')
    PartnerAdmin = apps.get_model('courses', 'PartnerAdmin')
    Link = apps.get_model('scholarship', 'ProgrammeReferralSource')

    owns_gift = Programme.objects.filter(organisation_id=OuterRef('pk'), is_active=True)
    has_org_admin = PartnerAdmin.objects.filter(
        owning_organisation_id=OuterRef('pk'), role='org_admin', is_active=True)
    sources = (PartnerOrganisation.objects
               .filter(show_in_apply=True, is_active=True)
               .exclude(Q(Exists(owns_gift)) | Q(Exists(has_org_admin)))
               .values_list('id', 'programme_id'))
    active_gifts = list(Programme.objects.filter(is_active=True).values_list('id', flat=True))

    wanted = set()
    for source_id, gift_id in sources:
        for programme_id in ([gift_id] if gift_id else active_gifts):
            wanted.add((programme_id, source_id))
    have = set(Link.objects.values_list('programme_id', 'source_id'))
    Link.objects.bulk_create([
        Link(programme_id=p, source_id=s) for p, s in sorted(wanted - have)
    ])


def unseed_programme_sources(apps, schema_editor):
    apps.get_model('scholarship', 'ProgrammeReferralSource').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0076_spm_prereq_selection'),
        ('scholarship', '0171_cohort_allowed_birth_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeReferralSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_source_links', to='scholarship.programme')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_links', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'programme_referral_sources',
                'ordering': ['programme_id', 'source_id'],
                'constraints': [models.UniqueConstraint(fields=('programme', 'source'), name='uniq_programme_referral_source')],
            },
        ),
        migrations.RunPython(seed_programme_sources, unseed_programme_sources),
    ]
