"""
The sponsor-facing generated profile, the interview trio, and a reopened decision.

Moved here VERBATIM from `apps/scholarship/models.py` at code health H15 (2026-09-20).
Moves only: no field, no `Meta`, no `db_table`, no `related_name` was touched, so the
database is untouched too — `makemigrations --check` reports no changes. See `__init__.py`.
"""
from django.db import models

from .applications import ScholarshipApplication

class SponsorProfile(models.Model):
    """The AI-drafted, admin-reviewed sponsor-facing profile for an application.
    The draft is generated by Gemini; an admin may edit it, then publish."""
    STATUS = [('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published')]
    application = models.OneToOneField(
        ScholarshipApplication, on_delete=models.CASCADE, related_name='sponsor_profile',
    )
    draft_markdown = models.TextField(blank=True, default='')
    edited_markdown = models.TextField(blank=True, default='')
    # Phase D: the "v2" profile — a second Gemini pass that refines the draft with
    # the submitted interview findings. Admin-facing for now (the sponsor consumer
    # is gated on Phase E). Kept separate from draft/edited so both stay visible.
    final_markdown = models.TextField(blank=True, default='')
    final_model_used = models.CharField(max_length=50, blank=True, default='')
    finalised_at = models.DateTimeField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=STATUS, default='draft')
    model_used = models.CharField(max_length=50, blank=True, default='')
    # profile_engine.PROMPT_VERSION that produced the current draft/final. Lets us detect a
    # stale draft by version (not by date) and target regeneration. '' = pre-versioning.
    prompt_version = models.CharField(max_length=30, blank=True, default='')
    generated_at = models.DateTimeField(null=True, blank=True)
    published_at = models.DateTimeField(null=True, blank=True)
    # ── Phase E2: the ANONYMOUS, sponsor-pool-facing profile ──────────────────
    # GENERATED (not scrubbed) from non-identifying inputs only — it must never
    # contain the student's name/school/town. Distinct from draft/edited/final
    # (which are the NAMED admin-facing write-ups). `anon_published` is the
    # sponsor-pool visibility gate: a profile appears in the pool only when it is
    # anon-published AND the application has an active share_with_sponsors consent.
    anon_markdown = models.TextField(blank=True, default='')
    anon_model_used = models.CharField(max_length=50, blank=True, default='')
    anon_generated_at = models.DateTimeField(null=True, blank=True)
    anon_published = models.BooleanField(default=False)
    anon_published_at = models.DateTimeField(null=True, blank=True)
    # A ≤20-word, CARD-STRICT one-liner for the sponsor-pool browse card (distinct from
    # anon_markdown, which is the fuller PII-redacted profile that MAY name school/town).
    # This must never carry name/school/town/state — generated by a strict prompt then
    # backstopped by scan_anon_for_identifiers. '' = none yet (the card shows course only).
    anon_blurb = models.CharField(max_length=200, blank=True, default='')
    # F3: stamped once this published student has been included in a real-time
    # sponsor alert batch, so the hourly job never re-sends them. Reset to null on
    # (re)publish so a freshly-published student is alerted exactly once.
    realtime_notified_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'sponsor_profiles'

    @property
    def current_markdown(self):
        """Edited text wins over the raw AI draft."""
        return self.edited_markdown or self.draft_markdown

    def __str__(self):
        return f'SponsorProfile #{self.application_id} ({self.status})'


class InterviewSession(models.Model):
    """Phase C: the structured record of a post-shortlist interview.

    The interview agenda is generated from the deterministic anomaly engine
    (apps/scholarship/anomaly_engine.detect_anomalies) — the same flags the admin
    "Pre-interview flags" card shows. ``findings`` records a closed-ended verdict
    + short rationale against each flag (and any manually-added concerns), so two
    reviewers rating the same applicant converge (the standardisation north star
    in docs/scholarship/post-shortlist-vision.md).
    """
    STATUS = [('draft', 'Draft'), ('submitted', 'Submitted')]
    application = models.ForeignKey(
        ScholarshipApplication, on_delete=models.CASCADE, related_name='interview_sessions',
    )
    interviewer = models.ForeignKey(
        'courses.PartnerAdmin', on_delete=models.SET_NULL, null=True, blank=True,
        related_name='interviews_conducted',
    )
    status = models.CharField(max_length=20, choices=STATUS, default='draft')
    # findings: { "<anomaly_code>": {"verdict": "resolved|still_unclear|new_concern",
    #             "rationale": "<=140 chars"} }. Keys are the codes from
    # detect_anomalies(); manually-added concerns use synthetic "manual_<n>" codes.
    findings = models.JSONField(default=dict, blank=True)
    # rubric: fixed 1-5 dimensions, e.g. {"clarity_of_plan": 4, "financial_need": 5,
    # "resilience": 3}. The inter-rater-reliability mechanism.
    rubric = models.JSONField(default=dict, blank=True)
    overall_note = models.TextField(blank=True, default='')
    started_at = models.DateTimeField(null=True, blank=True)
    submitted_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'interview_sessions'
        ordering = ['-created_at']

    def __str__(self):
        return f'InterviewSession #{self.application_id} ({self.status})'


class InterviewSlot(models.Model):
    """A single interview time the assigned reviewer PROPOSES to a student.

    Model: the reviewer offers 2-3 slots per applicant; the student picks one
    (which sets the booking state on ScholarshipApplication). Withdrawing an
    unbooked option flips is_active to False rather than deleting (keeps a record).
    Times are tz-aware (stored UTC, rendered in Asia/Kuala_Lumpur). The whole
    surface is dark behind INTERVIEW_SCHEDULING_ENABLED.
    """
    application = models.ForeignKey(
        ScholarshipApplication, on_delete=models.CASCADE, related_name='interview_slots',
    )
    reviewer = models.ForeignKey(
        'courses.PartnerAdmin', on_delete=models.CASCADE, related_name='proposed_interview_slots',
        help_text="The reviewer who proposed this slot (= the assigned reviewer).",
    )
    start = models.DateTimeField(help_text="Proposed interview start (tz-aware).")
    duration_min = models.PositiveSmallIntegerField(default=45)
    # False once withdrawn by the reviewer or superseded by a fresh proposal round.
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'interview_slots'
        ordering = ['start']

    def __str__(self):
        return f'InterviewSlot #{self.application_id} @ {self.start:%Y-%m-%d %H:%M}'


class InterviewMessage(models.Model):
    """A short free-text note from the STUDENT to their assigned reviewer.

    The always-open pressure valve around the scheduling flow: reschedule/cancel close
    inside the 12h cutoff, but "I'm running late" / "I'm sick" must still reach the
    reviewer — even one hour before the call. Stored for the cockpit thread + audit;
    delivery is a best-effort email to the assigned reviewer (the student never sees
    the reviewer's address). Rate-limited in scheduling.send_student_message.
    """
    application = models.ForeignKey(
        ScholarshipApplication, on_delete=models.CASCADE, related_name='interview_messages',
    )
    text = models.TextField(help_text="The student's message (capped at 1000 chars on write).")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'interview_messages'
        ordering = ['created_at']

    def __str__(self):
        return f'InterviewMessage #{self.application_id} @ {self.created_at:%Y-%m-%d %H:%M}'


class DecisionReopen(models.Model):
    """Audit row for each time a superadmin REOPENS a recorded decision.

    Reopening a finalised decision asserts the assigned REVIEWER made an error;
    while a row is OPEN (``closed_at`` is null) the application's decision panel is
    editable again and the sponsor profile is held from the pool. On close:
      - ``resulted_in_change=True``  → the reopen led to a re-saved decision (a real
        correction); this is what COUNTS against the reviewer.
      - ``resulted_in_change=False`` → it was cancelled/restored with no change.

    The per-reviewer "corrections" count = COUNT(resulted_in_change=True) over this
    log (counting model B, the owner's call 2026-06-18) — derived from the audit
    trail, never a bare counter that could drift.
    """
    application = models.ForeignKey(
        ScholarshipApplication, on_delete=models.CASCADE, related_name='decision_reopens',
    )
    # Attributed to the ASSIGNED reviewer at the moment of reopen (they own the
    # interview + recommendation). SET_NULL so deactivating an admin never destroys
    # the audit trail.
    reviewer = models.ForeignKey(
        'courses.PartnerAdmin', on_delete=models.SET_NULL, null=True, blank=True,
        related_name='decision_reopens_attributed',
        help_text="The reviewer the correction is attributed to (assigned reviewer at reopen).",
    )
    reopened_by = models.CharField(
        max_length=254, blank=True, default='',
        help_text="Email of the superadmin who reopened the decision.",
    )
    reason = models.TextField(help_text="Why the decision was reopened (the asserted reviewer error).")
    # Pool-publish state captured at reopen, so a cancel restores it exactly.
    was_published = models.BooleanField(default=False)
    # True once the reopen led to a re-saved decision (a real correction → counts).
    resulted_in_change = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    closed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'decision_reopens'
        ordering = ['-created_at']

    def __str__(self):
        state = 'open' if self.closed_at is None else 'closed'
        return f'DecisionReopen #{self.application_id} ({state})'
