# Generated by Django 5.2.11 on 2026-02-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(help_text='AI-generated report text')),
                ('summary', models.TextField(blank=True, help_text='Short summary')),
                ('student_profile_snapshot', models.JSONField(help_text='Copy of student profile at generation time')),
                ('eligible_courses_snapshot', models.JSONField(help_text='List of eligible courses at generation time')),
                ('model_used', models.CharField(help_text='gemini-pro, gpt-4, etc.', max_length=50)),
                ('generation_time_ms', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='courses.studentprofile')),
            ],
            options={
                'db_table': 'generated_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
