'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import Image from 'next/image'
import Link from 'next/link'
import Markdown from 'react-markdown'
import { getReport, type ReportDetail } from '@/lib/api'
import { getSession } from '@/lib/supabase'

export default function ReportPage() {
  const params = useParams()
  const reportId = Number(params.id)
  const [report, setReport] = useState<ReportDetail | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    async function loadReport() {
      try {
        const { session } = await getSession()
        if (!session?.access_token) {
          setError('Please log in to view your report.')
          setLoading(false)
          return
        }
        const data = await getReport(reportId, { token: session.access_token })
        setReport(data)
      } catch {
        setError('Failed to load report.')
      } finally {
        setLoading(false)
      }
    }
    loadReport()
  }, [reportId])

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-center">
          <div className="inline-block animate-spin rounded-full h-12 w-12 border-4 border-primary-500 border-t-transparent mb-4" />
          <p className="text-gray-600">Loading your report...</p>
        </div>
      </div>
    )
  }

  if (error || !report) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gray-50">
        <div className="text-center">
          <h1 className="text-2xl font-bold text-gray-900 mb-4">
            {error || 'Report not found'}
          </h1>
          <Link href="/dashboard" className="btn-primary">
            Back to Dashboard
          </Link>
        </div>
      </div>
    )
  }

  const formattedDate = new Date(report.created_at).toLocaleDateString('en-MY', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  })

  return (
    <main className="min-h-screen bg-gray-50">
      {/* Header — hidden in print */}
      <header className="bg-white border-b sticky top-0 z-10 print:hidden">
        <div className="container mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/dashboard" className="flex items-center gap-2">
            <Image src="/logo-icon.png" alt="" width={32} height={32} />
            <span className="font-semibold text-gray-900">HalaTuju</span>
          </Link>
          <div className="flex items-center gap-3">
            <Link href="/dashboard" className="text-gray-600 hover:text-gray-900 text-sm">
              Dashboard
            </Link>
            <button
              onClick={() => window.print()}
              className="btn-primary text-sm px-4 py-2"
            >
              Download PDF
            </button>
          </div>
        </div>
      </header>

      {/* Report Content */}
      <div className="container mx-auto px-6 py-8 max-w-3xl">
        {/* Report Header */}
        <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6 print:border-0 print:p-0 print:mb-4">
          <div className="flex items-center gap-3 mb-4 print:mb-2">
            <Image
              src="/logo-icon.png"
              alt=""
              width={40}
              height={40}
              className="hidden print:block"
            />
            <div>
              <h1 className="text-2xl font-bold text-gray-900 print:text-xl">
                {report.title}
              </h1>
              <p className="text-sm text-gray-500">
                {formattedDate}
              </p>
            </div>
          </div>
        </div>

        {/* Markdown Report Body */}
        <div className="bg-white rounded-xl border border-gray-200 p-8 print:border-0 print:p-0">
          <article className="prose prose-gray max-w-none
            prose-headings:text-gray-900 prose-headings:font-semibold
            prose-h2:text-xl prose-h2:mt-8 prose-h2:mb-4
            prose-h3:text-lg prose-h3:mt-6 prose-h3:mb-3
            prose-p:text-gray-700 prose-p:leading-relaxed
            prose-li:text-gray-700
            prose-strong:text-gray-900
            print:prose-sm"
          >
            <Markdown>{report.markdown}</Markdown>
          </article>
        </div>

        {/* Footer — print only */}
        <div className="hidden print:block mt-8 pt-4 border-t text-center text-xs text-gray-400">
          <p>Generated by HalaTuju AI Counsellor | halatuju.com | {formattedDate}</p>
        </div>
      </div>
    </main>
  )
}
