# Generated by Django 5.2.11 on 2026-02-15 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequirement',
            name='credit_math_or_addmath',
            field=models.BooleanField(default=False, help_text='Credit in Math or Add Math'),
        ),
        migrations.AddField(
            model_name='courserequirement',
            name='credit_sci',
            field=models.BooleanField(default=False, help_text='Credit in Science'),
        ),
        migrations.AddField(
            model_name='courserequirement',
            name='credit_science_group',
            field=models.BooleanField(default=False, help_text='Credit in Science group'),
        ),
        migrations.AddField(
            model_name='courserequirement',
            name='pass_sci',
            field=models.BooleanField(default=False, help_text='Pass Science'),
        ),
        migrations.AlterField(
            model_name='courserequirement',
            name='three_m_only',
            field=models.BooleanField(default=False, help_text='3M only: read/write/count'),
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='api_student_profiles',
        ),
    ]
