# Generated by Django 5.2.11 on 2026-02-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courserequirement_credit_math_or_addmath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courserequirement',
            name='source_type',
            field=models.CharField(choices=[('poly', 'Polytechnic'), ('kkom', 'Community College'), ('tvet', 'TVET/ILKBS/ILJTM'), ('ua', 'University/Asasi'), ('pismp', 'PISMP/Teacher Training')], default='poly', max_length=20),
        ),
    ]
