# Generated by Django 5.2.11 on 2026-02-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_pismp_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='modifiers',
            field=models.JSONField(blank=True, default=dict, help_text='Ranking modifiers: urban, cultural_safety_net, etc.'),
        ),
    ]
