# Generated by Django 5.2.11 on 2026-02-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_institution_modifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascoOccupation',
            fields=[
                ('masco_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('job_title', models.CharField(help_text='Official Malay job title', max_length=255)),
                ('emasco_url', models.URLField(blank=True, help_text='Link to eMASCO portal page', max_length=500)),
            ],
            options={
                'db_table': 'masco_occupations',
                'ordering': ['masco_code'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='career_occupations',
            field=models.ManyToManyField(blank=True, help_text='MASCO occupation codes this course leads to', related_name='courses', to='courses.mascooccupation'),
        ),
    ]
