# Generated by Django 5.2.11 on 2026-02-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_add_masco_occupations'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='headline',
            field=models.TextField(blank=True, default='', help_text='Catchy student-friendly headline'),
        ),
    ]
