# Generated by Django 5.2.11 on 2026-02-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_add_bilingual_description_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Student's full name", max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.CharField(blank=True, default='', help_text='SPM school name', max_length=255),
        ),
    ]
