# Generated by Django 5.2.11 on 2026-02-22 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_name_school_to_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20)),
                ('intake_year', models.IntegerField(blank=True, null=True)),
                ('intake_session', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('outcome_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='courses.course')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outcomes', to='courses.institution')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='courses.studentprofile')),
            ],
            options={
                'db_table': 'admission_outcomes',
                'ordering': ['-updated_at'],
                'unique_together': {('student', 'course', 'institution')},
            },
        ),
    ]
