# Generated by Django 5.2.11 on 2026-03-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_add_admission_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Home address'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='family_income',
            field=models.CharField(blank=True, default='', help_text='Family monthly income range', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nric',
            field=models.CharField(blank=True, default='', help_text='NRIC: XXXXXX-XX-XXXX', max_length=14),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='siblings',
            field=models.IntegerField(blank=True, help_text='Number of siblings', null=True),
        ),
    ]
