# Generated by Django 5.2.11 on 2026-03-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_expand_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedcourse',
            name='interest_status',
            field=models.CharField(choices=[('interested', 'Interested'), ('planning', 'Planning to apply'), ('applied', 'Applied'), ('got_offer', 'Got offer')], default='interested', help_text="Student's self-reported interest level", max_length=20),
        ),
    ]
