# Generated by Django 5.2.11 on 2026-03-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_add_interest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StpmCourse',
            fields=[
                ('program_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=500)),
                ('university', models.CharField(max_length=255)),
                ('stream', models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('both', 'Both')], default='both', max_length=20)),
            ],
            options={
                'db_table': 'stpm_courses',
                'ordering': ['university', 'program_name'],
            },
        ),
        migrations.CreateModel(
            name='StpmRequirement',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='requirement', serialize=False, to='courses.stpmcourse')),
                ('min_cgpa', models.FloatField(default=2.0)),
                ('stpm_min_subjects', models.IntegerField(default=2)),
                ('stpm_min_grade', models.CharField(default='C', max_length=5)),
                ('stpm_req_pa', models.BooleanField(default=False)),
                ('stpm_req_math_t', models.BooleanField(default=False)),
                ('stpm_req_math_m', models.BooleanField(default=False)),
                ('stpm_req_physics', models.BooleanField(default=False)),
                ('stpm_req_chemistry', models.BooleanField(default=False)),
                ('stpm_req_biology', models.BooleanField(default=False)),
                ('stpm_req_economics', models.BooleanField(default=False)),
                ('stpm_req_accounting', models.BooleanField(default=False)),
                ('stpm_req_business', models.BooleanField(default=False)),
                ('stpm_subject_group', models.JSONField(blank=True, null=True)),
                ('spm_credit_bm', models.BooleanField(default=False)),
                ('spm_pass_sejarah', models.BooleanField(default=False)),
                ('spm_credit_bi', models.BooleanField(default=False)),
                ('spm_pass_bi', models.BooleanField(default=False)),
                ('spm_credit_math', models.BooleanField(default=False)),
                ('spm_pass_math', models.BooleanField(default=False)),
                ('spm_credit_addmath', models.BooleanField(default=False)),
                ('spm_credit_science', models.BooleanField(default=False)),
                ('spm_subject_group', models.JSONField(blank=True, null=True)),
                ('min_muet_band', models.IntegerField(default=1)),
                ('req_interview', models.BooleanField(default=False)),
                ('no_colorblind', models.BooleanField(default=False)),
                ('req_medical_fitness', models.BooleanField(default=False)),
                ('req_malaysian', models.BooleanField(default=False)),
                ('req_bumiputera', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'stpm_requirements',
                'indexes': [models.Index(fields=['min_cgpa'], name='idx_stpm_req_min_cgpa')],
            },
        ),
    ]
