# Generated by Django 5.2.11 on 2026-03-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_stpmcourse_stpmrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='exam_type',
            field=models.CharField(choices=[('spm', 'SPM'), ('stpm', 'STPM')], default='spm', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='muet_band',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spm_prereq_grades',
            field=models.JSONField(blank=True, default=dict, help_text="SPM prerequisite grades for STPM students: {'bm': 'A', 'eng': 'B+', ...}"),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stpm_cgpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='stpm_grades',
            field=models.JSONField(blank=True, default=dict, help_text="STPM grades: {'PA': 'A', 'MATH_T': 'B+', ...}"),
        ),
    ]
