# Generated by Django 5.2.11 on 2026-03-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_studentprofile_exam_type_studentprofile_muet_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stpmcourse',
            name='merit_score',
            field=models.FloatField(blank=True, help_text='UPU average merit percentage (0-100)', null=True),
        ),
    ]
