# Generated by Django 5.2.11 on 2026-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_stpmcourse_merit_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='stpmcourse',
            name='category',
            field=models.CharField(blank=True, default='', help_text='AI-assigned category (Malay)', max_length=255),
        ),
        migrations.AddField(
            model_name='stpmcourse',
            name='description',
            field=models.TextField(blank=True, default='', help_text='AI-generated programme description'),
        ),
        migrations.AddField(
            model_name='stpmcourse',
            name='field',
            field=models.CharField(blank=True, default='', help_text='AI-assigned field category', max_length=255),
        ),
    ]
