# Generated by Django 5.2.11 on 2026-03-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_stpm_metadata_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequirement',
            name='merit_type',
            field=models.CharField(choices=[('standard', 'Standard SPM merit'), ('matric', 'Matriculation grade points'), ('stpm_mata_gred', 'STPM mata gred')], default='standard', help_text='Merit calculation formula to use', max_length=20),
        ),
        migrations.AlterField(
            model_name='courserequirement',
            name='source_type',
            field=models.CharField(choices=[('poly', 'Polytechnic'), ('kkom', 'Community College'), ('tvet', 'TVET/ILKBS/ILJTM'), ('ua', 'University/Asasi'), ('pismp', 'PISMP/Teacher Training'), ('matric', 'Matriculation'), ('stpm', 'STPM/Form 6')], default='poly', max_length=20),
        ),
    ]
