# Generated by Django 5.2.11 on 2026-03-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_insert_preu_institutions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stpmcourse',
            options={'ordering': ['university', 'course_name']},
        ),
        migrations.AlterField(
            model_name='stpmcourse',
            name='program_id',
            field=models.CharField(db_column='program_id', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='stpmcourse',
            old_name='program_id',
            new_name='course_id',
        ),
        migrations.AlterField(
            model_name='stpmcourse',
            name='program_name',
            field=models.CharField(db_column='program_name', max_length=500),
        ),
        migrations.RenameField(
            model_name='stpmcourse',
            old_name='program_name',
            new_name='course_name',
        ),
        migrations.AlterField(
            model_name='stpmcourse',
            name='description',
            field=models.TextField(blank=True, default='', help_text='AI-generated course description'),
        ),
    ]
