# Generated by Django 5.2.11 on 2026-03-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_rename_stpm_program_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stpmcourse',
            name='course_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stpmcourse',
            name='course_name',
            field=models.CharField(max_length=500),
        ),
    ]
