# Generated by Django 5.2.11 on 2026-03-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_stpm_db_column_workaround'),
    ]

    operations = [
        migrations.AddField(
            model_name='stpmcourse',
            name='mohe_url',
            field=models.URLField(blank=True, default='', help_text='Link to MOHE ePanduan programme page', max_length=500),
        ),
    ]
