# Generated by Django 5.2.11 on 2026-03-14 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_add_stpm_mohe_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stpmcourse',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Linked institution (resolved from university name)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stpm_courses', to='courses.institution'),
        ),
    ]
