# Generated by Django 5.2.11 on 2026-03-14 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_add_stpm_institution_fk'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedcourse',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='savedcourse',
            name='stpm_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.stpmcourse'),
        ),
        migrations.AlterField(
            model_name='savedcourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddConstraint(
            model_name='savedcourse',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('stpm_course__isnull', True)), models.Q(('course__isnull', True), ('stpm_course__isnull', False)), _connector='OR'), name='exactly_one_course_type'),
        ),
    ]
