# Generated by Django 5.2.11 on 2026-03-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_saved_course_dual_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='stpmcourse',
            name='headline',
            field=models.CharField(blank=True, default='', help_text='Quirky BM headline for student-facing subtitle', max_length=200),
        ),
    ]
