# Generated by Django 5.2.11 on 2026-03-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_add_stpm_headline'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTaxonomy',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ms', models.CharField(max_length=100)),
                ('name_ta', models.CharField(max_length=100)),
                ('image_slug', models.CharField(help_text='Supabase Storage filename (without .png)', max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('parent_key', models.ForeignKey(blank=True, help_text='Parent group for dropdown grouping (~9 top-level groups)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='courses.fieldtaxonomy')),
            ],
            options={
                'db_table': 'field_taxonomy',
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='field_key',
            field=models.ForeignKey(blank=True, help_text='Canonical field classification', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='courses.fieldtaxonomy'),
        ),
        migrations.AddField(
            model_name='stpmcourse',
            name='field_key',
            field=models.ForeignKey(blank=True, help_text='Canonical field classification', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stpm_courses', to='courses.fieldtaxonomy'),
        ),
    ]
