# Generated by Django 5.2.11 on 2026-03-16 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_field_key_non_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='frontend_label',
        ),
    ]
