# Generated by Django 5.2.11 on 2026-03-16 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_remove_course_frontend_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stpmcourse',
            name='category',
        ),
    ]
