# Generated by Django 5.2.11 on 2026-03-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_remove_stpmcourse_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stpmcourse',
            name='career_occupations',
            field=models.ManyToManyField(blank=True, help_text='MASCO occupation codes this programme leads to', related_name='stpm_courses', to='courses.mascooccupation'),
        ),
    ]
