# Generated by Django 5.2.11 on 2026-03-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_add_stpm_career_occupations'),
    ]

    operations = [
        migrations.AddField(
            model_name='stpmrequirement',
            name='no_disability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stpmrequirement',
            name='req_female',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stpmrequirement',
            name='req_male',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stpmrequirement',
            name='single',
            field=models.BooleanField(default=False),
        ),
    ]
