# Generated by Django 5.2.11 on 2026-03-16 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_partner_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Raw referral code or chip value (e.g. cumig, whatsapp, google)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='referred_by_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_students', to='courses.partnerorganisation'),
        ),
    ]
