# Generated by Django 5.2.11 on 2026-03-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_stpmrequirement_no_disability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='URL slug: cumig, partner2', max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'partner_organisations',
                'ordering': ['name'],
            },
        ),
    ]
