# Generated by Django 5.2.11 on 2026-03-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_student_profile_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='admin_org_code',
            field=models.CharField(blank=True, default='', help_text='If set, this user is an admin for the given partner org code', max_length=50),
        ),
    ]
