# Generated by Django 5.2.11 on 2026-03-16 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_student_profile_admin_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supabase_user_id', models.CharField(blank=True, help_text='Set on first login via UID or email match', max_length=100, null=True, unique=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, help_text='NULL for super admin', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='courses.partnerorganisation')),
            ],
            options={
                'db_table': 'partner_admins',
            },
        ),
    ]
