# Generated by Django 5.2.11 on 2026-03-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_student_profile_admin_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='angka_giliran',
            field=models.CharField(blank=True, default='', help_text='University application ref: AB123C456', max_length=9),
        ),
    ]
