# Generated by Django 5.2.11 on 2026-03-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_partneradmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='admin_org_code',
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
