# Generated by Django 5.2.11 on 2026-03-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_remove_studentprofile_admin_org_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneradmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
