# Generated by Django 5.2.11 on 2026-03-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_add_partner_admin_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Verified contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='contact_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', help_text='Verified contact phone', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='contact_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('nric', ''), _negated=True), fields=('nric',), name='unique_nric_when_set'),
        ),
    ]
