# Generated by Django 5.2.11 on 2026-03-17 04:06

from django.db import migrations


def migrate_phone_data(apps, schema_editor):
    StudentProfile = apps.get_model('courses', 'StudentProfile')
    for profile in StudentProfile.objects.exclude(phone=''):
        profile.contact_phone = profile.phone
        profile.save(update_fields=['contact_phone'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_studentprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_phone_data, migrations.RunPython.noop),
    ]
