# Generated by Django 5.2.11 on 2026-03-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_add_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stpmrequirement',
            name='min_muet_band',
            field=models.FloatField(default=1.0),
        ),
    ]
