# Generated by Django 5.2.11 on 2026-03-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_stpm_muet_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City/town (auto-filled from postcode)', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='5-digit Malaysian postcode', max_length=5),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Street address'),
        ),
    ]
