# Generated by Django 5.2.11 on 2026-03-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_add_postal_code_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtaxonomy',
            name='riasec_primary',
            field=models.CharField(blank=True, choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], default='', help_text='Primary Holland RIASEC type for this field', max_length=1),
        ),
        migrations.AddField(
            model_name='stpmcourse',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='', help_text='Programme difficulty for resilience matching', max_length=10),
        ),
        migrations.AddField(
            model_name='stpmcourse',
            name='efficacy_domain',
            field=models.CharField(blank=True, choices=[('quantitative', 'Quantitative'), ('scientific', 'Scientific'), ('verbal', 'Verbal'), ('practical', 'Practical')], default='', help_text='Primary cognitive domain for efficacy matching', max_length=15),
        ),
        migrations.AddField(
            model_name='stpmcourse',
            name='riasec_type',
            field=models.CharField(blank=True, choices=[('R', 'Realistic'), ('I', 'Investigative'), ('A', 'Artistic'), ('S', 'Social'), ('E', 'Enterprising'), ('C', 'Conventional')], default='', help_text='Primary Holland RIASEC type for this programme', max_length=1),
        ),
    ]
