# Generated by Django 5.2.11 on 2026-03-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_add_riasec_difficulty_efficacy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stpmcourse',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = removed from MOHE, hidden from search/eligibility'),
        ),
    ]
