# Generated by Django 5.2.11 on 2026-03-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_stpmcourse_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='colorblind',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='disability',
            field=models.BooleanField(default=False),
        ),
    ]
