# Generated by Django 5.2.11 on 2026-05-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_convert_colorblind_disability_to_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='guardians',
            field=models.JSONField(blank=True, default=list, help_text='Guardian details: [{name, relationship, occupation, income}]'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='household_income',
            field=models.IntegerField(blank=True, help_text='Combined monthly household income in RM', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='household_size',
            field=models.IntegerField(blank=True, help_text='Number of people in the household', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='receives_jkm',
            field=models.BooleanField(default=False, help_text='Receives JKM assistance'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='receives_str',
            field=models.BooleanField(default=False, help_text='Active Sumbangan Tunai Rahmah recipient (B40 anchor)'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='family_income',
            field=models.CharField(blank=True, default='', help_text='Family monthly income range (legacy/coarse)', max_length=30),
        ),
    ]
