# Generated by Django 5.2.11 on 2026-05-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0047_studentprofile_guardians_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='unique_nric_when_set',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='coq_score',
            field=models.FloatField(blank=True, help_text='Co-curricular score out of 10 (entered at onboarding, feeds merit); persisted so it pre-fills the scholarship Results section.', null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nric_verified',
            field=models.BooleanField(default=False, help_text="True once an admin verifies the NRIC against the uploaded MyKad (then it locks). Until then the NRIC stays editable and is NOT uniqueness-enforced. See docs/decisions.md (supersedes 'IC immutable')."),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_call_language',
            field=models.CharField(blank=True, default='', help_text='Preferred language for phone calls: en/ms/ta/mixed (B40 outreach).', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('nric_verified', True), models.Q(('nric', ''), _negated=True)), fields=('nric',), name='unique_verified_nric'),
        ),
    ]
