# Generated by Django 5.2.11 on 2026-05-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0048_remove_studentprofile_unique_nric_when_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='stream_subjects',
            field=models.JSONField(blank=True, default=list, help_text="The SPM subjects the student studied as their stream/aliran (e.g. ['phy','chem','bio','addmath']). When present, the merit engine uses these as the Sec2 (30% stream) candidates instead of guessing the stream from the pools (TD-063). Empty = fall back to the count-heuristic (existing/historical profiles)."),
        ),
    ]
