# Generated by Django 5.2.11 on 2026-05-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0049_studentprofile_stream_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='family_income',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='siblings',
        ),
    ]
