# Generated by Django 5.2.11 on 2026-05-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0050_remove_studentprofile_family_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneradmin',
            name='role',
            field=models.CharField(choices=[('super', 'Super admin'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], default='reviewer', help_text='Phase C: super/reviewer/viewer. Backfilled from is_super_admin.', max_length=20),
        ),
    ]
