# Generated by Django 5.2.11 on 2026-05-31 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_partneradmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='elective_subjects',
            field=models.JSONField(blank=True, default=list, help_text="The SPM subjects the student picked as electives/tambahan (e.g. ['ekonomi','poa']). The durable record of *which* subjects are electives — without it, the onboarding grades form can't reconstruct the elective selection after logout/login and drops those grades. Up to 7 (a student may sit many subjects). The merit engine still uses only the best 2 (Sec3, 10%); the rest persist for course-specific eligibility."),
        ),
    ]
