# Generated by Django 5.2.11 on 2026-06-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_studentprofile_elective_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneradmin',
            name='role',
            field=models.CharField(choices=[('super', 'Super admin'), ('admin', 'Admin'), ('partner', 'Partner'), ('reviewer', 'Reviewer')], default='reviewer', help_text='super / admin / partner / reviewer. Backfilled from is_super_admin.', max_length=20),
        ),
    ]
