# Generated by Django 5.2.11 on 2026-06-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_alter_partneradmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = MOHE no longer lists this programme (soft-delete, never hard-deleted; see docs/decisions.md). Set by sync_spm_mohe. NOTE: read paths are intentionally NOT yet filtered by this — detail/search still show inactive courses until a later sprint wires the filter (mirrors StpmCourse), so the golden master is unaffected.'),
        ),
    ]
