# Generated by Django 5.2.11 on 2026-06-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0055_coursedatastatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='father_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_occupation',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_occupation_other',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_occupation',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_occupation_other',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='other_family_members',
            field=models.JSONField(blank=True, default=list, help_text='Brother/sister/guardian pool: [{role, occupation, occupation_other?}]'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='siblings_in_school',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='siblings_in_tertiary',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
