# Generated by Django 5.2.11 on 2026-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0056_studentprofile_father_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='chosen_pathway',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='chosen_programme',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pathway_certainty',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pathways_considered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pre_u_institution',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pre_u_track',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='uncertainty_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='uncertainty_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
