# Generated by Django 5.2.11 on 2026-06-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_courserequirement_req_disability'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=True),
        ),
    ]
