# Generated by Django 5.2.15 on 2026-07-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_alter_partneradmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganisation',
            name='brand_colour',
            field=models.CharField(blank=True, default='', help_text="Hex colour, e.g. '#137fec'; '' = platform default", max_length=20),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='email_from',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='email_reply_to',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='email_support',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='frontend_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='logo_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='module_comms_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='module_payout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='module_scholarship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='module_sponsor_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='persona_name_en',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='persona_name_ms',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='persona_name_ta',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='programme_name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='programme_name_ms',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='programme_name_ta',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='team_signoff_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='team_signoff_ms',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='team_signoff_ta',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
