# Generated by Django 5.2.15 on 2026-07-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0061_partnerorganisation_brand_colour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneradmin',
            name='owning_organisation',
            field=models.ForeignKey(blank=True, help_text='Tenant org this staff member is scoped to for B40 access (NULL = platform-level: super/partner). Never the referral org.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to='courses.partnerorganisation'),
        ),
    ]
