# Generated by Django 5.2.15 on 2026-07-18 22:20

from django.db import migrations, models


def seed_live_referral_sources(apps, schema_editor):
    """Turn ON show_in_apply for every organisation that has actually referred a student
    (any StudentProfile.referred_by_org points at it). On prod this is exactly the 6 live
    referral orgs (SMC, CUMIG, MHM, EWRF, PPT6M, HSS — verified 2026-07-19); data-driven
    rather than a hard-coded code list so it can't drift from the real referral graph.
    Idempotent and reversible (the reverse just clears the flag)."""
    PartnerOrganisation = apps.get_model('courses', 'PartnerOrganisation')
    StudentProfile = apps.get_model('courses', 'StudentProfile')
    referred_ids = (StudentProfile.objects
                    .filter(referred_by_org__isnull=False)
                    .values_list('referred_by_org_id', flat=True)
                    .distinct())
    PartnerOrganisation.objects.filter(id__in=list(referred_ids)).update(show_in_apply=True)


def clear_show_in_apply(apps, schema_editor):
    PartnerOrganisation = apps.get_model('courses', 'PartnerOrganisation')
    PartnerOrganisation.objects.update(show_in_apply=False)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0064_partneradmin_org_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerorganisation',
            name='show_in_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(seed_live_referral_sources, clear_show_in_apply),
    ]
