# Generated by Django 5.2.15 on 2026-07-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0065_partnerorganisation_show_in_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partneradmin',
            name='role',
            field=models.CharField(choices=[('super', 'Super admin'), ('admin', 'Admin'), ('org_admin', 'Organisation admin'), ('partner', 'Partner'), ('reviewer', 'Reviewer'), ('qc', 'Quality control'), ('finance', 'Finance admin')], default='reviewer', help_text='super / admin / partner / reviewer. Backfilled from is_super_admin.', max_length=20),
        ),
    ]
