# Generated by Django 5.2.15 on 2026-08-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_reconcile_module_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneradmin',
            name='paused_at',
            field=models.DateTimeField(blank=True, help_text='When this reviewer stepped back. NULL = participating. Blocks NEW assignment only — never sign-in, and never work already theirs. NOT a revoke: that is is_active.', null=True),
        ),
    ]
