# Generated by Django 5.2.15 on 2026-08-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0068_reviewer_paused_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneradmin',
            name='first_seen_at',
            field=models.DateTimeField(blank=True, help_text='First time this person opened the console. Set once, never updated — it is what closes their invitation. NULL means not recorded, not "never came".', null=True),
        ),
        migrations.AddField(
            model_name='partneradmin',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='Most recent console session, throttled to about once a day. Answers "are they still with us?". NULL means not recorded.', null=True),
        ),
    ]
