# Generated by Django 5.2.15 on 2026-09-03 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0072_alter_organisationtheme_options_and_more'),
        ('scholarship', '0149_s_assign_programme_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='partneradmin',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Gift programme this person is scoped to. NULL = every gift the organisation runs, which is the default and what every existing staff member has.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='scholarship.programme'),
        ),
        migrations.AddField(
            model_name='partnerorganisation',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Gift programme whose apply form lists this source. NULL = every gift, which is the default and what every existing source has.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_sources', to='scholarship.programme'),
        ),
    ]
