# Generated by Django 5.2.15 on 2026-09-19 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """TD-254 — TWO NEW TABLES for the rebuilt profile claim. Purely additive: no existing
    table is altered, no data migration, nothing is backfilled.

    ⚠ MIGRATE-FIRST. `sqlmigrate` renders SQLite here, so run the Postgres DDL below against
    production BEFORE the push, then record the `django_migrations` row.

        CREATE TABLE profile_claim_events (
            id bigserial PRIMARY KEY,
            created_at timestamptz NOT NULL,
            caller_sub varchar(100) NOT NULL,
            target_profile_id varchar(100) NOT NULL DEFAULT '',
            nric varchar(20) NOT NULL DEFAULT '',
            event varchar(40) NOT NULL,
            channel varchar(16) NOT NULL DEFAULT '',
            actor varchar(100) NOT NULL DEFAULT ''
        );
        CREATE INDEX profile_claim_events_created_at_827fd304
            ON profile_claim_events (created_at);
        CREATE INDEX profile_claim_events_caller_sub_f380d065
            ON profile_claim_events (caller_sub);
        CREATE INDEX profile_claim_events_target_profile_id_68e5aaf1
            ON profile_claim_events (target_profile_id);
        CREATE INDEX profile_claim_events_nric_98a9e552
            ON profile_claim_events (nric);
        CREATE INDEX profile_cla_nric_9755b4_idx
            ON profile_claim_events (nric, created_at);
        ALTER TABLE profile_claim_events ENABLE ROW LEVEL SECURITY;
        CREATE POLICY service_role_all ON profile_claim_events
            FOR ALL TO service_role USING (true) WITH CHECK (true);

        CREATE TABLE profile_login_aliases (
            alias_uid varchar(100) PRIMARY KEY,
            created_at timestamptz NOT NULL,
            claim_event_id bigint NULL
                REFERENCES profile_claim_events (id) DEFERRABLE INITIALLY DEFERRED,
            profile_id varchar(100) NOT NULL
                REFERENCES api_student_profiles (supabase_user_id) DEFERRABLE INITIALLY DEFERRED
        );
        CREATE INDEX profile_login_aliases_claim_event_id_82e9accb
            ON profile_login_aliases (claim_event_id);
        CREATE INDEX profile_login_aliases_profile_id_48fd61ef
            ON profile_login_aliases (profile_id);
        ALTER TABLE profile_login_aliases ENABLE ROW LEVEL SECURITY;
        CREATE POLICY service_role_all ON profile_login_aliases
            FOR ALL TO service_role USING (true) WITH CHECK (true);

    ⚠ VERIFY THE REFERENCED TABLE NAME BEFORE RUNNING THE FK LINE. `StudentProfile` sets its
    own `db_table`; confirm it is `api_student_profiles` on production rather than assuming the
    Django default. The 2026-06-01 `api_student_profiles` incident is the precedent — a bare
    ALTER against a guessed table name silently hit a real, different table.

    ⚠ `profile_login_aliases.profile_id` CASCADES. Deleting a profile therefore removes the
    aliases pointing at it, and those logins fall back to their own (empty) record — fail
    closed, never somebody else's. `profile_claim_events` holds `target_profile_id` as a PLAIN
    column precisely so the audit line outlives the profile it names.

    ⚠ EVERY NEW TABLE ON THIS PROJECT CARRIES RLS WITH EXACTLY ONE service_role POLICY (the
    `rls_auto_enable` event trigger switches RLS on; it adds no policy). The same statements
    are recorded in `apps/scholarship/sql/rls_policies.sql`. Run the Security Advisor after.
    """

    dependencies = [
        ('courses', '0074_organisationconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('caller_sub', models.CharField(db_index=True, max_length=100)),
                ('target_profile_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('nric', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('event', models.CharField(max_length=40)),
                ('channel', models.CharField(blank=True, default='', max_length=16)),
                ('actor', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'profile_claim_events',
                'indexes': [models.Index(fields=['nric', 'created_at'], name='profile_cla_nric_9755b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProfileLoginAlias',
            fields=[
                ('alias_uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim_event', models.ForeignKey(blank=True, help_text='The `claimed` event that created this alias.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aliases', to='courses.profileclaimevent')),
                ('profile', models.ForeignKey(help_text='The profile this login acts as. Deleting THIS row reverses the claim.', on_delete=django.db.models.deletion.CASCADE, related_name='login_aliases', to='courses.studentprofile')),
            ],
            options={
                'db_table': 'profile_login_aliases',
            },
        ),
    ]
