# Generated by Django 5.2.15 on 2026-10-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    """TD-069 (Now sprint 4, 2026-10-02) — TWO ADDITIVE COLUMNS on `api_student_profiles`, so an
    STPM student's SPM-prerequisite entry rebuilds after logout/login. No table is created, no
    data is migrated, nothing is backfilled (nothing ever synced `spm_prereq_grades` from the web
    before this sprint, so there is no history to recover — the same outcome as v2.21's 0052).

    ⚠ MIGRATE-FIRST. `sqlmigrate` renders SQLite here, so run this Postgres DDL against
    production BEFORE the push. The table is `api_student_profiles` — read from
    `StudentProfile.Meta.db_table`, NOT guessed: a legacy `student_profiles` table also exists and
    a bare ALTER against it succeeds silently (the 2026-05-31 v2.21 incident, TD-025).

        ALTER TABLE api_student_profiles
            ADD COLUMN spm_elective_subjects jsonb NOT NULL DEFAULT '[]'::jsonb;
        ALTER TABLE api_student_profiles
            ADD COLUMN spm_stream varchar(20) NOT NULL DEFAULT '';

    ⚠ KEEP BOTH DEFAULTS — do not follow Django's own `ALTER ... DROP DEFAULT`. The columns exist
    while the OLD image is still serving, and the old code inserts profiles without naming them;
    without a database default every new sign-up between the migrate and the deploy would fail
    on NOT NULL. A leftover default is harmless to Django.

    Then record the ledger row:

        INSERT INTO django_migrations (app, name, applied)
            VALUES ('courses', '0076_spm_prereq_selection', now());

    Additive columns on an existing table need no new RLS policy (the table already carries one).
    """

    dependencies = [
        ('courses', '0075_profile_claim_alias_and_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='spm_elective_subjects',
            field=models.JSONField(blank=True, default=list, help_text='STPM path: which spm_prereq_grades keys are SPM electives (up to 7).'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='spm_stream',
            field=models.CharField(blank=True, default='', help_text='STPM path: the SPM stream picked for the prerequisites (science/arts/technical).', max_length=20),
        ),
    ]
